const $=s=>document.querySelector(s), c=$('#clock'), modal=$('#connect-modal'), toast=$('#toast');
    const release=window.LIFE_HUB_RELEASE;
    const releaseLabel=release?.version?`v${release.version}${release.releasedAt?` · ${release.releasedAt}`:''}`:'版本信息缺失';
    document.querySelectorAll('[data-app-version]').forEach(element=>{element.textContent=releaseLabel});
    const projectUrl='https://github.com/Guyao146/homeassistant-web',versionSources=[`${projectUrl}/raw/main/version.js`,`${projectUrl}/raw/master/version.js`];
    let OIDC=null;
    const redirectUri=location.origin+location.pathname;
    let HA=null;
    async function loadRuntimeConfig(){
      const config=window.LIFE_HUB_CONFIG;
      const missing=[];
      if(!config?.oidc?.clientId)missing.push('oidc.clientId');
      if(!config?.oidc?.authorize)missing.push('oidc.authorize');
      if(!config?.oidc?.token)missing.push('oidc.token');
      if(!config?.homeAssistant?.url)missing.push('homeAssistant.url');
      if(!config?.homeAssistant?.token)missing.push('homeAssistant.token');
      if(missing.length)throw new Error(`config.js 配置缺失：${missing.join('、')}`);
      OIDC={...config.oidc};
      HA={...config.homeAssistant,url:String(config.homeAssistant.url).replace(/\/$/,'')};
    }
    const b64url=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
    async function pkce(){const bytes=crypto.getRandomValues(new Uint8Array(48)),verifier=b64url(bytes),digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));return {verifier,challenge:b64url(digest)}}
    function loginError(m){$('#auth-error').textContent=m}
    function setLoginReady(ready){const button=$('#auth-login');button.disabled=!ready;if(ready&&$('#auth-error').textContent.includes('配置'))loginError('')}
    async function signIn(){
      if(!OIDC)throw new Error('登录配置尚未加载完成');
      if(!window.isSecureContext)throw new Error('Authentik 登录需要 HTTPS 部署（localhost 除外）');
      const {verifier,challenge}=await pkce(),state=b64url(crypto.getRandomValues(new Uint8Array(20)));
      sessionStorage.setItem('life-hub-pkce',JSON.stringify({verifier,state}));
      const p=new URLSearchParams({client_id:OIDC.clientId,response_type:'code',redirect_uri:redirectUri,scope:'openid profile email',state,code_challenge:challenge,code_challenge_method:'S256'});
      location.assign(OIDC.authorize+'?'+p)
    }
    function enterDashboard(){
      sessionStorage.setItem('life-hub-dashboard-access','true');
      $('#auth-gate').classList.add('hidden');
      $('#app-loader').classList.add('hidden')
    }
    function readSession(key){try{return JSON.parse(sessionStorage.getItem(key)||'null')}catch(err){sessionStorage.removeItem(key);return null}}
    async function authenticate(){
      const params=new URLSearchParams(location.search),stored=readSession('life-hub-oidc');
      if(params.get('error')){
        sessionStorage.removeItem('life-hub-pkce');
        throw new Error(`验证服务拒绝登录：${params.get('error_description')||params.get('error')}`);
      }
      if(sessionStorage.getItem('life-hub-dashboard-access')==='true'||stored?.expiresAt>Date.now()){
        enterDashboard();
        return true
      }
      if(!params.get('code')){
        $('#app-loader').classList.add('hidden');
        return false
      }
      const pending=readSession('life-hub-pkce');
      if(!pending||pending.state!==params.get('state'))throw new Error('登录状态校验失败，请重新登录');
      const form=new URLSearchParams({grant_type:'authorization_code',client_id:OIDC.clientId,code:params.get('code'),redirect_uri:redirectUri,code_verifier:pending.verifier});
      const response=await fetch(OIDC.token,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form});
      if(!response.ok){sessionStorage.removeItem('life-hub-pkce');throw new Error('验证服务未接受登录请求，请检查回调地址、客户端类型和 CORS 设置')}
      const tokens=await response.json();
      if(!tokens?.access_token)throw new Error('验证服务返回的登录结果缺少 access_token');
      sessionStorage.setItem('life-hub-oidc',JSON.stringify({...tokens,expiresAt:Date.now()+(tokens.expires_in||3600)*1000}));
      sessionStorage.removeItem('life-hub-pkce');
      history.replaceState({},document.title,redirectUri);enterDashboard();return true
    }
    $('#auth-login').onclick=()=>{
      loginError('正在跳转到 验证服务…');
      signIn().catch(e=>loginError(e.message))
    };
    $('#auth-continue')?.addEventListener('click',enterDashboard);
    function logout(){
      sessionStorage.removeItem('life-hub-oidc');
      sessionStorage.removeItem('life-hub-pkce');
      sessionStorage.removeItem('life-hub-dashboard-access');
      location.assign(redirectUri)
    }
    $('#auth-logout').onclick=logout;
    const displayNameKey='life-hub-display-name',defaultDisplayName='Gu';
    let renderedDate='',renderedGreeting='';
    function displayName(){try{return (localStorage.getItem(displayNameKey)||defaultDisplayName).trim().slice(0,24)||defaultDisplayName}catch(err){return defaultDisplayName}}
    function greetingForHour(hour){if(hour<5)return '深夜好';if(hour<11)return '早上好';if(hour<13)return '中午好';if(hour<17)return '下午好';if(hour<19)return '傍晚好';if(hour<23)return '晚上好';return '深夜好'}
    function renderGreeting(d){const text=`${greetingForHour(d.getHours())}，${displayName()}`;if(text===renderedGreeting)return;renderedGreeting=text;$('#greeting').textContent=text}
    function renderLocalDate(d){
      const weekdays=['星期日','星期一','星期二','星期三','星期四','星期五','星期六'], shortDays=['日','一','二','三','四','五','六'];
      $('#today').textContent=`${d.getMonth()+1} 月 ${d.getDate()} 日，${weekdays[d.getDay()]}`;
      const eta=new Date(d.getTime()+40*60*1000);$('#delivery-eta').textContent=eta.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});
      const monday=new Date(d);monday.setHours(0,0,0,0);monday.setDate(d.getDate()-((d.getDay()+6)%7));
      $('#habit-grid').innerHTML=Array.from({length:7},(_,i)=>{const day=new Date(monday);day.setDate(monday.getDate()+i);return `<div class="day ${i<((d.getDay()+6)%7)?'done':''}">${shortDays[day.getDay()]}<b>${day.getDate()}</b><i class="check"></i></div>`}).join('');
      [...$('#energy-bars').querySelectorAll('em')].forEach((label,i)=>{const day=new Date(d);day.setDate(d.getDate()-(3-i));label.textContent=i===3?'今天':`周${shortDays[day.getDay()]}`});
    }
    function tick(){const d=new Date();c.textContent=d.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});renderGreeting(d);const dateKey=d.toDateString();if(dateKey!==renderedDate){renderedDate=dateKey;renderLocalDate(d)}} tick();setInterval(tick,1000);
    function notice(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)}
    function showModal(){modal.classList.add('show')} function hideModal(){modal.classList.remove('show')}
    $('#settings-connect').onclick=showModal; $('#cancel-connect').onclick=hideModal;
    modal.addEventListener('click',e=>{if(e.target===modal)hideModal()});
    $('#quick-picker').onclick=()=>openPicker();$('#cancel-picker').onclick=()=>$('#picker-modal').classList.remove('show');$('#picker-modal').onclick=e=>{if(e.target===$('#picker-modal'))$('#picker-modal').classList.remove('show')};$('#save-picker').onclick=()=>{const ids=[...$('#picker-list').querySelectorAll('input:checked')].map(input=>input.value).slice(0,6);saveQuickIds(ids);renderQuick(latestStates);$('#picker-modal').classList.remove('show');notice('快捷控制已保存')};
    $('#close-detail').onclick=()=>$('#device-modal').classList.remove('show');$('#device-modal').onclick=e=>{if(e.target===$('#device-modal'))$('#device-modal').classList.remove('show')};$('#detail-control').onclick=()=>{if(selectedDetail)controlEntity(selectedDetail)};$('#device-search').oninput=()=>renderDevices(latestStates);
    const widgetKey='life-hub-widgets',layoutKey='life-hub-layout',navKey='life-hub-hidden-nav',widgetNames={home:'家庭环境',delivery:'外卖配送',agenda:'今日日程',quick:'快捷控制',devices:'HA 区域与场景',habit:'本周习惯',energy:'能量使用'},navNames={home:'我的家',schedule:'日程',orders:'消费与订单',health:'健康'};
    const viewMeta={overview:{eyebrow:'LIFE OVERVIEW',title:'总览',description:'在一个页面中查看今天最重要的生活信息。'},home:{eyebrow:'SMART HOME',title:'我的家',description:'查看家庭环境、设备状态与常用场景。'},schedule:{eyebrow:'DAILY PLAN',title:'日程',description:'集中查看今天的日历事件、任务与安排。'},orders:{eyebrow:'ORDERS & SPENDING',title:'消费与订单',description:'跟踪配送进度、消费记录与家庭能耗。'},health:{eyebrow:'WELLNESS',title:'健康',description:'记录习惯、状态与持续改善的生活目标。'},settings:{eyebrow:'CONTROL CENTER',title:'设置',description:'管理你在看板中显示的内容和连接。'}};
    let activeView='overview';
    const defaultOrder=Object.keys(widgetNames),defaultSizes={home:'medium',delivery:'small',agenda:'medium',quick:'small',devices:'large',habit:'medium',energy:'small'},sizeNames={small:'小',medium:'中',large:'大'};
    function hiddenWidgets(){try{const value=JSON.parse(localStorage.getItem(widgetKey)||'[]');return new Set(Array.isArray(value)?value:[])}catch(err){localStorage.removeItem(widgetKey);return new Set()}}
    function hiddenNavItems(){try{const value=JSON.parse(localStorage.getItem(navKey)||'[]');return new Set(Array.isArray(value)?value.filter(id=>navNames[id]):[])}catch(err){localStorage.removeItem(navKey);return new Set()}}
    function layout(){try{const saved=JSON.parse(localStorage.getItem(layoutKey)||'{}'),order=Array.isArray(saved.order)?saved.order.filter(id=>defaultOrder.includes(id)):[],sizes=saved.sizes&&typeof saved.sizes==='object'?saved.sizes:{};return {order:[...order,...defaultOrder.filter(id=>!order.includes(id))],sizes}}catch(err){localStorage.removeItem(layoutKey);return {order:defaultOrder.slice(),sizes:{}}}}
    function saveLayout(next){try{localStorage.setItem(layoutKey,JSON.stringify(next))}catch(err){notice('无法保存组件布局')}}
    function currentWidgetSize(id){const saved=layout().sizes[id];return sizeNames[saved]?saved:(defaultSizes[id]||'medium')}
    function updateCardDraggable(card){if(!card)return;card.draggable=false;const handle=card.querySelector('.widget-drag-handle');if(handle)handle.draggable=window.innerWidth>900&&!card.querySelector('.widget-menu.is-open')}
    function widgetPopover(menu){return document.getElementById(menu.dataset.popoverId)}
    function closeWidgetMenus(except=null){document.querySelectorAll('.widget-menu.is-open').forEach(menu=>{if(menu===except)return;menu.classList.remove('is-open');widgetPopover(menu)?.classList.remove('is-open');menu.querySelector('.widget-menu-trigger').setAttribute('aria-expanded','false');updateCardDraggable(menu.closest('[data-widget-id]'))})}
    function refreshWidgetMenus(){document.querySelectorAll('.widget-menu').forEach(menu=>{const current=currentWidgetSize(menu.closest('[data-widget-id]').dataset.widgetId);widgetPopover(menu)?.querySelectorAll('[data-widget-size]').forEach(button=>{const active=button.dataset.widgetSize===current;button.classList.toggle('active',active);button.setAttribute('aria-checked',String(active))})})}
    function positionWidgetMenu(menu){const trigger=menu.querySelector('.widget-menu-trigger'),popover=widgetPopover(menu);if(!popover)return;const rect=trigger.getBoundingClientRect(),width=window.innerWidth<=580?180:164,height=popover.offsetHeight||132;popover.style.left=Math.max(10,Math.min(window.innerWidth-width-10,rect.right-width))+'px';popover.style.top=(rect.bottom+8+height<=window.innerHeight?rect.bottom+8:Math.max(10,rect.top-height-8))+'px'}
    function setupWidgetMenus(){document.querySelectorAll('.grid>[data-widget-id]').forEach(card=>{if(card.querySelector('.widget-menu'))return;const id=card.dataset.widgetId,popoverId=`widget-size-menu-${id}`,handle=document.createElement('span');handle.className='widget-drag-handle';handle.setAttribute('role','img');handle.setAttribute('aria-label',`拖动${widgetNames[id]}组件`);handle.title='按住拖动组件';handle.innerHTML='<i></i><i></i><i></i><i></i><i></i><i></i>';const menu=document.createElement('div');menu.className='widget-menu';menu.dataset.popoverId=popoverId;menu.innerHTML=`<button class="widget-menu-trigger" type="button" title="调整组件尺寸" aria-label="调整${widgetNames[id]}尺寸" aria-haspopup="menu" aria-controls="${popoverId}" aria-expanded="false">⋮</button>`;const popover=document.createElement('div');popover.id=popoverId;popover.className='widget-menu-popover';popover.setAttribute('role','menu');popover.setAttribute('aria-label',`${widgetNames[id]}组件尺寸`);popover.innerHTML=Object.entries(sizeNames).map(([value,name])=>`<button type="button" role="menuitemradio" data-widget-size="${value}"><span class="size-preview size-${value}"></span><span>${name}卡</span><small>${value==='small'?'1 列':value==='medium'?'2 列':'3 列'}</small></button>`).join('');document.body.append(popover);menu.querySelector('.widget-menu-trigger').onclick=e=>{e.stopPropagation();const open=!menu.classList.contains('is-open');closeWidgetMenus(menu);menu.classList.toggle('is-open',open);popover.classList.toggle('is-open',open);e.currentTarget.setAttribute('aria-expanded',String(open));updateCardDraggable(card);if(open){refreshWidgetMenus();requestAnimationFrame(()=>positionWidgetMenu(menu))}};popover.querySelectorAll('[data-widget-size]').forEach(button=>button.onclick=e=>{e.stopPropagation();const next=layout();next.sizes[id]=button.dataset.widgetSize;saveLayout(next);applyLayout();closeWidgetMenus();if(activeView==='settings')renderWidgetSettings();notice(`${widgetNames[id]}已调整为${sizeNames[button.dataset.widgetSize]}卡`)});card.querySelector('.card-head').append(handle,menu);updateCardDraggable(card)});refreshWidgetMenus()}
    function applyLayout(){const grid=$('.grid'),current=layout();current.order.forEach(id=>{const card=grid.querySelector(`[data-widget-id="${id}"]`);if(card)grid.append(card)});grid.querySelectorAll('[data-widget-id]').forEach(card=>{const size=current.sizes[card.dataset.widgetId]||defaultSizes[card.dataset.widgetId]||'medium';card.classList.remove('size-small','size-medium','size-large');card.classList.add('size-'+(sizeNames[size]?size:'medium'));updateCardDraggable(card)});refreshWidgetMenus()}
    function applyNavVisibility(){const hidden=hiddenNavItems();document.querySelectorAll('.sidebar .nav [data-view]').forEach(item=>item.classList.toggle('nav-item-hidden',hidden.has(item.dataset.view)))}
    function applyView(){const hidden=hiddenWidgets();applyLayout();applyNavVisibility();document.querySelectorAll('.grid>[data-widget-id]').forEach(card=>{const inView=activeView==='overview'||card.dataset.views.split(' ').includes(activeView);card.classList.toggle('is-hidden',!inView||hidden.has(card.dataset.widgetId))});$('.grid').classList.toggle('is-hidden',activeView==='settings');$('.settings-page').classList.toggle('is-active',activeView==='settings')}
    function renderWidgetSettings(){const hidden=hiddenWidgets(),current=layout(),root=$('#widget-settings');root.innerHTML=current.order.map(id=>`<div class="widget-setting-row"><label class="widget-toggle"><span><b>${widgetNames[id]}</b><small>${hidden.has(id)?'已隐藏':'显示在看板中'}</small></span><input type="checkbox" value="${id}" ${hidden.has(id)?'':'checked'}><i></i></label><select class="widget-size" data-size-id="${id}" aria-label="${widgetNames[id]}尺寸">${Object.entries(sizeNames).map(([value,name])=>`<option value="${value}" ${(current.sizes[id]||defaultSizes[id]||'medium')===value?'selected':''}>${name}卡</option>`).join('')}</select></div>`).join('');root.querySelectorAll('input').forEach(input=>input.onchange=()=>{const before=new Map(visibleCards().map(card=>[card,card.getBoundingClientRect()])),next=hiddenWidgets();input.checked?next.delete(input.value):next.add(input.value);localStorage.setItem(widgetKey,JSON.stringify([...next]));renderWidgetSettings();applyView();animateViewChange(before)});root.querySelectorAll('.widget-size').forEach(select=>select.onchange=()=>{const next=layout();next.sizes[select.dataset.sizeId]=select.value;saveLayout(next);applyView();notice(`${widgetNames[select.dataset.sizeId]}已调整为${sizeNames[select.value]}卡`)})}
    function renderNavSettings(){const hidden=hiddenNavItems(),root=$('#nav-settings');root.innerHTML=Object.entries(navNames).map(([id,name])=>`<label class="widget-toggle"><span><b>${name}</b><small>${hidden.has(id)?'已从左侧隐藏':'显示在左侧导航'}</small></span><input type="checkbox" value="${id}" ${hidden.has(id)?'':'checked'}><i></i></label>`).join('');root.querySelectorAll('input').forEach(input=>input.onchange=()=>{const next=hiddenNavItems();input.checked?next.delete(input.value):next.add(input.value);localStorage.setItem(navKey,JSON.stringify([...next]));applyNavVisibility();renderNavSettings();notice(`${navNames[input.value]}已${input.checked?'显示':'隐藏'}`)})}
    function syncProfileSettings(){$('#profile-name').value=displayName()}
    function visibleCards(){return [...document.querySelectorAll('.grid>[data-widget-id]:not(.is-hidden)')]}
    function animateViewChange(before){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;requestAnimationFrame(()=>visibleCards().forEach((card,index)=>{if(typeof card.animate!=='function')return;const start=before.get(card);if(!start){card.animate([{transform:'translateY(18px) scale(.985)',opacity:0},{transform:'translateY(0) scale(1)',opacity:1}],{duration:380,delay:Math.min(index*35,175),easing:'cubic-bezier(.22,1,.36,1)',fill:'backwards'});return}const end=card.getBoundingClientRect(),dx=start.left-end.left,dy=start.top-end.top;if(Math.abs(dx)<1&&Math.abs(dy)<1)return;card.animate([{transform:`translate(${dx}px,${dy}px)`,opacity:.72},{transform:'translate(0, 0)',opacity:1}],{duration:380,easing:'cubic-bezier(.22,1,.36,1)'})}))}
    function animateSettingsView(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const page=$('.settings-page');if(typeof page.animate!=='function')return;page.animate([{transform:'translateY(14px)',opacity:0},{transform:'translateY(0)',opacity:1}],{duration:360,easing:'cubic-bezier(.22,1,.36,1)'});page.querySelectorAll('.settings-card').forEach((card,index)=>card.animate([{transform:'translateY(16px) scale(.99)',opacity:0},{transform:'translateY(0) scale(1)',opacity:1}],{duration:420,delay:70+index*45,easing:'cubic-bezier(.22,1,.36,1)',fill:'backwards'}))}
    function renderViewIntro(view,animate=true){const meta=viewMeta[view]||viewMeta.overview,elements=[$('#view-eyebrow'),$('#view-title'),$('#view-description')];elements[0].textContent=meta.eyebrow;elements[1].textContent=meta.title;elements[2].textContent=meta.description;if(!animate||matchMedia('(prefers-reduced-motion: reduce)').matches)return;elements.forEach((element,index)=>{if(typeof element.animate!=='function')return;element.getAnimations().forEach(animation=>animation.cancel());element.animate([{transform:'translateY(10px)',opacity:0,filter:'blur(3px)'},{transform:'translateY(0)',opacity:1,filter:'blur(0)'}],{duration:360,delay:index*48,easing:'cubic-bezier(.22,1,.36,1)',fill:'backwards'})})}
    async function checkForUpdate(){const status=$('#version-status'),button=$('#check-update');if(!status||!button)return;button.disabled=true;status.textContent='正在检查 GitHub…';try{let remoteText='';for(const source of versionSources){const response=await fetch(`${source}?t=${Date.now()}`,{cache:'no-store'});if(response.ok){remoteText=await response.text();break}}if(!remoteText)throw new Error('无法读取远程版本');const match=remoteText.match(/version:\s*['"]([^'"]+)['"]/);const remoteVersion=match?.[1];if(!remoteVersion)throw new Error('远程版本格式无法识别');if(remoteVersion!==release?.version){status.textContent=`发现新版本 v${remoteVersion}`;notice(`发现新版本 v${remoteVersion}，点击 GitHub 查看`)}else{status.textContent='已是最新版本';notice('当前已经是最新版本')}}catch(error){status.textContent='检查失败，请稍后重试';notice('暂时无法检查 GitHub 更新')}finally{button.disabled=false}}
    function setView(view){if(view===activeView)return;const before=new Map(visibleCards().map(card=>[card,card.getBoundingClientRect()]));activeView=view;document.querySelectorAll('[data-view]').forEach(item=>{const isActive=item.dataset.view===view;item.classList.toggle('active',isActive);if(item.closest('.nav,.mobile-nav'))item.setAttribute('aria-current',isActive?'page':'false')});renderViewIntro(view);applyView();if(view==='settings'){renderWidgetSettings();renderNavSettings();syncProfileSettings();requestAnimationFrame(animateSettingsView)}else animateViewChange(before);window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
    document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>setView(button.dataset.view));
    $('#profile-form').onsubmit=e=>{e.preventDefault();const name=$('#profile-name').value.trim().replace(/\s+/g,' ').slice(0,24);if(!name){notice('请输入你希望显示的称呼');$('#profile-name').focus();return}try{localStorage.setItem(displayNameKey,name)}catch(err){notice('浏览器阻止了称呼保存');return}$('#profile-name').value=name;renderedGreeting='';renderGreeting(new Date());notice('称呼已保存')};
    $('#settings-reset').onclick=()=>{localStorage.removeItem(widgetKey);localStorage.removeItem(layoutKey);localStorage.removeItem(navKey);localStorage.removeItem('life-hub-quick');localStorage.removeItem(environmentSlotsKey);renderWidgetSettings();renderNavSettings();renderEnvironmentSlots(latestStates);setView('overview');notice('布局、小组件、导航和环境数据位已恢复默认')};
    const grid=$('.grid');let draggedCard=null;const reorderAnimations=new WeakMap();
    setupWidgetMenus();
    document.addEventListener('click',()=>closeWidgetMenus());document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;closeWidgetMenus();closeEnvironmentPicker();$('#picker-modal').classList.remove('show');$('#device-modal').classList.remove('show')});window.addEventListener('resize',()=>{applyLayout();closeWidgetMenus()});
    function animateCardReorder(target,before){const cards=[...grid.querySelectorAll('[data-widget-id]')],first=new Map(cards.map(card=>[card,card.getBoundingClientRect()])),reference=before?target:target.nextSibling;if(reference===draggedCard||draggedCard.nextSibling===reference)return;target.parentNode.insertBefore(draggedCard,reference);cards.forEach(card=>{if(card===draggedCard)return;const start=first.get(card),end=card.getBoundingClientRect(),dx=start.left-end.left,dy=start.top-end.top;if(Math.abs(dx)<1&&Math.abs(dy)<1)return;reorderAnimations.get(card)?.cancel();if(typeof card.animate!=='function')return;const animation=card.animate([{transform:`translate(${dx}px,${dy}px)`},{transform:'translate(0, 0)'}],{duration:190,easing:'cubic-bezier(.2,.8,.2,1)'});reorderAnimations.set(card,animation);animation.onfinish=()=>{if(reorderAnimations.get(card)===animation)reorderAnimations.delete(card)}})}
    function dragGhost(card){const ghost=document.createElement('div');ghost.className='widget-drag-ghost';ghost.textContent=card.querySelector('h2')?.textContent||widgetNames[card.dataset.widgetId];document.body.append(ghost);return ghost}
    grid.addEventListener('dragstart',e=>{const handle=e.target.closest('.widget-drag-handle'),card=handle?.closest('[data-widget-id]');if(!handle||!card||window.innerWidth<=900){e.preventDefault();return}closeWidgetMenus();draggedCard=card;const ghost=dragGhost(card);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',card.dataset.widgetId);e.dataTransfer.setDragImage(ghost,18,18);requestAnimationFrame(()=>{card.classList.add('is-dragging');ghost.remove()})});
    grid.addEventListener('dragover',e=>{const target=e.target.closest('[data-widget-id]');if(!draggedCard||!target||target===draggedCard)return;e.preventDefault();e.dataTransfer.dropEffect='move';const rect=target.getBoundingClientRect(),before=Math.abs(e.clientY-(rect.top+rect.height/2))>rect.height*.25?e.clientY<rect.top+rect.height/2:e.clientX<rect.left+rect.width/2;animateCardReorder(target,before)});
    grid.addEventListener('dragend',()=>{if(!draggedCard)return;draggedCard.classList.remove('is-dragging');saveLayout({...layout(),order:[...grid.querySelectorAll('[data-widget-id]')].map(card=>card.dataset.widgetId)});draggedCard=null;notice('组件位置已保存')});
    $('#settings-logout').onclick=logout;
    $('#check-update').onclick=checkForUpdate;
    applyView();
    $('#refresh-home').onclick=()=>{registrySyncedAt=0;return sync({}).then(()=>notice('已刷新 Home Assistant 数据')).catch(err=>notice(err.message))};
    document.querySelectorAll('.more:not(#refresh-home):not(#quick-picker):not(#close-detail):not(#close-environment-picker)').forEach(button=>button.onclick=()=>notice('该数据源尚未接入，可继续扩展'));
    let syncTimer=null, syncing=false, latestStates=[], selectedDetail=null,activeEnvironmentSlot=0,registry={areas:[],devices:[],entities:[]},registrySyncedAt=0;
    const environmentSlotsKey='life-hub-environment-slots';
    const controllableDomains=['light','switch','fan','climate','vacuum','cover','media_player','lock','input_boolean','button','input_button','script','automation','siren','humidifier','water_heater'];
    const deviceGroups={light:['灯光','☼'],switch:['开关','⏻'],fan:['风扇','◉'],climate:['空调与温控','♨'],vacuum:['清洁设备','◔'],cover:['窗帘与遮阳','▤'],media_player:['媒体设备','♬'],lock:['门锁','⌑'],input_boolean:['虚拟开关','◌'],button:['按钮','●'],input_button:['按钮','●'],script:['脚本','▷'],automation:['自动化','↻'],siren:['警报器','!'],humidifier:['加湿器','≈'],water_heater:['热水器','♨']};
    const canControl=s=>Boolean(s?.entity_id)&&controllableDomains.includes(s.entity_id.split('.')[0])&&!['unknown','unavailable'].includes(s.state);
    function entity(states, domain, words=[]){return states.find(s=>s.entity_id.startsWith(domain+'.') && (words.length===0||words.some(w=>(s.attributes.friendly_name||s.entity_id).toLowerCase().includes(w))))}
    function value(s){return s?.state && !['unknown','unavailable'].includes(s.state) ? s.state : null}
    function label(s){return s.attributes.friendly_name||s.entity_id.split('.').pop().replaceAll('_',' ')}
    function environmentSensorKind(s){
      if(!s?.entity_id?.startsWith('sensor.'))return null;
      const deviceClass=String(s.attributes?.device_class||'').toLowerCase(),unit=String(s.attributes?.unit_of_measurement||'').trim().toLowerCase(),name=`${s.entity_id} ${s.attributes?.friendly_name||''}`.toLowerCase();
      if(deviceClass==='temperature'||/温度|temperature|temp/.test(name)||['°c','℃','°f'].includes(unit))return 'temperature';
      if(deviceClass==='humidity'||/湿度|humidity/.test(name))return 'humidity';
      return null
    }
    function environmentSensors(states,kind=null){return (Array.isArray(states)?states:[]).filter(s=>{const detected=environmentSensorKind(s);return detected&&(!kind||detected===kind)}).sort((a,b)=>label(a).localeCompare(label(b),'zh-CN'))}
    function savedEnvironmentIds(){try{const ids=JSON.parse(localStorage.getItem(environmentSlotsKey)||'[]');return Array.from({length:2},(_,index)=>Array.isArray(ids)&&typeof ids[index]==='string'?ids[index]:'')}catch(err){localStorage.removeItem(environmentSlotsKey);return ['','']}}
    function saveEnvironmentIds(ids){try{localStorage.setItem(environmentSlotsKey,JSON.stringify(Array.from({length:2},(_,index)=>ids[index]||'')))}catch(err){notice('浏览器阻止了环境传感器选择保存')}}
    function defaultEnvironmentIds(states){const temperature=environmentSensors(states,'temperature')[0]?.entity_id||'',humidity=environmentSensors(states,'humidity')[0]?.entity_id||'',all=environmentSensors(states);return [temperature||all[0]?.entity_id||'',humidity||all[1]?.entity_id||all[0]?.entity_id||'']}
    function resolvedEnvironmentIds(states){const saved=savedEnvironmentIds(),defaults=defaultEnvironmentIds(states),resolved=saved.map((id,index)=>id||defaults[index]);if(resolved.some((id,index)=>id!==saved[index]))saveEnvironmentIds(resolved);return resolved}
    function environmentSensorValue(s){const current=value(s);if(current===null)return '不可用';const unit=s.attributes?.unit_of_measurement||({temperature:'°C',humidity:'%'})[environmentSensorKind(s)]||'';return `${current}${unit}`}
    function renderEnvironmentSlots(states){const safeStates=Array.isArray(states)?states:[],ids=resolvedEnvironmentIds(safeStates);document.querySelectorAll('[data-environment-slot]').forEach((button,index)=>{const sensor=safeStates.find(s=>s.entity_id===ids[index]),name=button.querySelector('span'),reading=button.querySelector('strong');name.textContent=sensor?label(sensor):`环境数据 ${index+1}`;reading.textContent=sensor?environmentSensorValue(sensor):'点击选择';button.title=sensor?`${sensor.entity_id} · 点击更换`:`选择第 ${index+1} 个环境传感器`;button.setAttribute('aria-label',button.title)})}
    function environmentSensorOption(s,selectedId){const area=entityArea(s),meta=[area?.name,s.entity_id].filter(Boolean).join(' · ');return `<label class="environment-sensor-option"><input type="radio" name="environment-sensor" value="${escapeHtml(s.entity_id)}" ${s.entity_id===selectedId?'checked':''}><span class="environment-sensor-copy"><b>${escapeHtml(label(s))}</b><small title="${escapeHtml(meta)}">${escapeHtml(meta)}</small></span><span class="environment-sensor-value">${escapeHtml(environmentSensorValue(s))}</span></label>`}
    function renderEnvironmentSensorGroup(kind,title,icon,selectedId){const sensors=environmentSensors(latestStates,kind);return `<section class="environment-sensor-group"><h3><span>${icon}</span>${title}<small>${sensors.length} 个</small></h3><div class="environment-sensor-options">${sensors.length?sensors.map(s=>environmentSensorOption(s,selectedId)).join(''):`<div class="environment-sensor-empty">未发现${title}实体</div>`}</div></section>`}
    function closeEnvironmentPicker(){$('#environment-picker-modal').classList.remove('show')}
    function openEnvironmentPicker(index){activeEnvironmentSlot=Number(index)||0;const selectedId=resolvedEnvironmentIds(latestStates)[activeEnvironmentSlot];$('#environment-slot-kicker').textContent=`环境数据 ${activeEnvironmentSlot+1}`;$('#environment-picker-list').innerHTML=renderEnvironmentSensorGroup('temperature','温度','◒',selectedId)+renderEnvironmentSensorGroup('humidity','湿度','≈',selectedId);$('#environment-picker-modal').classList.add('show')}
    function quickIds(){try{const ids=JSON.parse(localStorage.getItem('life-hub-quick')||'[]');return Array.isArray(ids)?ids:[]}catch(err){localStorage.removeItem('life-hub-quick');return []}}
    function saveQuickIds(ids){try{localStorage.setItem('life-hub-quick',JSON.stringify(ids))}catch(err){notice('无法保存快捷设备，但本次选择仍可使用')}}
    function sceneLabel(s){return label(s).replace(/场景$/,'').trim()||label(s)}
    function isActive(s){return !['off','closed','locked','idle','docked','standby','paused','unknown','unavailable'].includes(String(s?.state).toLowerCase())}
    function entityIcon(s){return s.entity_id.startsWith('scene.')?'✦':(deviceGroups[s.entity_id.split('.')[0]]||['','◉'])[1]}
    function renderQuick(states){const safeStates=Array.isArray(states)?states:[],eligible=safeStates.filter(canControl);let ids=quickIds().filter(id=>eligible.some(s=>s.entity_id===id));if(!ids.length)ids=eligible.slice(0,4).map(s=>s.entity_id);const chosen=ids.map(id=>safeStates.find(s=>s.entity_id===id)).filter(Boolean),grid=$('#quick-grid');grid.innerHTML='';if(!chosen.length){grid.innerHTML='<div class="empty-picker">未发现可控设备，请检查 Home Assistant 实体状态。</div>';return}chosen.forEach(s=>grid.append(makeQuick(s)))}
    function entityArea(s){const entry=registry.entities.find(item=>item.entity_id===s.entity_id),device=entry?.device_id?registry.devices.find(item=>item.id===entry.device_id):null,areaId=entry?.area_id||device?.area_id||null;return areaId?registry.areas.find(item=>item.area_id===areaId||item.id===areaId):null}
    function appendEntityButton(root,s){const button=document.createElement('button');button.type='button';if(s.entity_id.startsWith('scene.')){button.className='device-item scene-item';button.innerHTML=`<span class="scene-icon">✦</span><span class="scene-copy"><strong>${escapeHtml(sceneLabel(s))}</strong><small>${escapeHtml(s.entity_id)}</small></span><span class="scene-action">执行</span>`;button.onclick=()=>runScene(s)}else{button.className='device-item';button.innerHTML=`<strong>${escapeHtml(label(s))}</strong><small class="${isActive(s)?'state-on':''}">${escapeHtml(s.state)} · ${escapeHtml(s.entity_id)}</small>`;button.onclick=()=>openDevice(s)}root.append(button)}
    function renderDevices(states){const safeStates=Array.isArray(states)?states:[],query=$('#device-search').value.trim().toLowerCase(),list=$('#device-list'),scenes=safeStates.filter(s=>s.entity_id.startsWith('scene.')),nonScenes=safeStates.filter(s=>!s.entity_id.startsWith('scene.')),groups=[];if(scenes.length)groups.push({id:'scenes',name:'场景',icon:'✦',items:scenes});registry.areas.slice().sort((a,b)=>String(a.name).localeCompare(String(b.name),'zh-CN')).forEach(area=>groups.push({id:area.area_id||area.id,name:area.name,icon:'⌂',items:nonScenes.filter(s=>(entityArea(s)?.area_id||entityArea(s)?.id)===(area.area_id||area.id))}));const assigned=new Set(groups.flatMap(group=>group.items.map(s=>s.entity_id))),unassigned=nonScenes.filter(s=>!assigned.has(s.entity_id));if(unassigned.length)groups.push({id:'unassigned',name:registry.areas.length?'未分配区域':'全部实体（区域信息未加载）',icon:'◉',items:unassigned});const filtered=groups.map(group=>{const areaMatch=group.name.toLowerCase().includes(query);return {...group,items:areaMatch?group.items:group.items.filter(s=>(`${label(s)} ${s.entity_id} ${s.state}`).toLowerCase().includes(query))}}).filter(group=>group.items.length||(!query&&group.id!=='unassigned'));$('#device-count').textContent=`${safeStates.length} 个实体 · ${registry.areas.length} 个区域 · ${scenes.length} 个场景`;list.innerHTML='';if(!filtered.length){list.innerHTML='<div class="empty-picker">没有匹配的区域、设备或场景。</div>';return}filtered.forEach(group=>{const details=document.createElement('details');details.className='device-group ha-device-group';details.open=Boolean(query)||group.id==='scenes';details.innerHTML=`<summary><span class="device-group-icon">${group.icon}</span><span>${escapeHtml(group.name)}</span><small>${group.items.length} 个实体</small></summary><div class="device-items"></div>`;group.items.forEach(s=>appendEntityButton(details.querySelector('.device-items'),s));list.append(details)})}
    function openDevice(s){selectedDetail=s;const area=entityArea(s);$('#detail-name').textContent=label(s);$('#detail-state').textContent=s.state;const attrs=[...(area?[['区域',area.name]]:[]),...Object.entries(s.attributes||{}).filter(([k])=>k!=='friendly_name').slice(0,19)];$('#detail-attrs').innerHTML=attrs.map(([k,v])=>`<div><span>${escapeHtml(k)}</span><b>${escapeHtml(typeof v==='object'?JSON.stringify(v):v)}</b></div>`).join('')||'<div><span>没有额外属性</span></div>';$('#detail-control').textContent=controlLabel(s);$('#detail-control').style.display=canControl(s)?'inline-block':'none';$('#device-modal').classList.add('show')}
    function updatePickerCount(){const inputs=[...$('#picker-list').querySelectorAll('input:checked')];$('#picker-count').textContent=`${inputs.length} / 6`;return inputs.length}
    function openPicker(){const selected=new Set(quickIds()),list=$('#picker-list'),groups=new Map();latestStates.filter(canControl).forEach(s=>{const domain=s.entity_id.split('.')[0];if(!groups.has(domain))groups.set(domain,[]);groups.get(domain).push(s)});list.innerHTML='';if(!groups.size)list.innerHTML='<div class="empty-picker">暂无可添加的可控设备，请先连接 Home Assistant。</div>';groups.forEach((states,domain)=>{const [name,icon]=deviceGroups[domain]||['其他设备','◉'],details=document.createElement('details');details.className='device-group';details.open=states.some(s=>selected.has(s.entity_id));details.innerHTML=`<summary><span class="device-group-icon">${icon}</span><span>${name}</span><small>${states.length} 个设备</small></summary><div class="picker-options">${states.map(s=>`<label class="picker-option"><input type="checkbox" value="${escapeHtml(s.entity_id)}" ${selected.has(s.entity_id)?'checked':''}><span title="${escapeHtml(s.entity_id)}">${escapeHtml(label(s))}</span></label>`).join('')}</div>`;list.append(details)});list.querySelectorAll('input').forEach(input=>input.onchange=()=>{if(updatePickerCount()>6){input.checked=false;updatePickerCount();notice('快捷控制最多选择 6 个设备')}});updatePickerCount();$('#picker-modal').classList.add('show')}
    document.querySelectorAll('[data-environment-slot]').forEach(button=>button.onclick=()=>openEnvironmentPicker(button.dataset.environmentSlot));
    $('#close-environment-picker').onclick=closeEnvironmentPicker;
    $('#cancel-environment-picker').onclick=closeEnvironmentPicker;
    $('#environment-picker-modal').onclick=e=>{if(e.target===$('#environment-picker-modal'))closeEnvironmentPicker()};
    $('#save-environment-picker').onclick=()=>{const selected=$('#environment-picker-list input[name="environment-sensor"]:checked');if(!selected){notice('请先选择一个温度或湿度传感器');return}const ids=savedEnvironmentIds();ids[activeEnvironmentSlot]=selected.value;saveEnvironmentIds(ids);renderEnvironmentSlots(latestStates);closeEnvironmentPicker();notice(`环境数据 ${activeEnvironmentSlot+1} 已保存`)};
    function makeQuick(s){const active=isActive(s),b=document.createElement('button');b.className=active?'on':'';b.innerHTML=`<span class="qicon">${entityIcon(s)}</span><span class="qname">${escapeHtml(label(s))}</span><small>${['button','input_button','script'].includes(s.entity_id.split('.')[0])?'点击执行':active?'已开启':'已关闭'}</small>`;b.onclick=()=>controlEntity(s);return b}
    async function runScene(scene){try{await api('/api/services/scene/turn_on',{}, {method:'POST',body:JSON.stringify({entity_id:scene.entity_id})});notice(`已执行「${sceneLabel(scene)}」`)}catch(err){notice(err.message)}}
    function controlAction(s){const domain=s.entity_id.split('.')[0],active=isActive(s);if(domain==='cover')return active?'close_cover':'open_cover';if(domain==='lock')return s.state==='unlocked'?'lock':'unlock';if(domain==='vacuum')return ['cleaning','returning'].includes(s.state)?'return_to_base':'start';if(['button','input_button'].includes(domain))return 'press';if(domain==='script')return 'turn_on';return active?'turn_off':'turn_on'}
    function controlLabel(s){const action=controlAction(s);return ({close_cover:'关闭',open_cover:'打开',lock:'上锁',unlock:'解锁',return_to_base:'返回充电',start:'启动',press:'按下',turn_on:'开启',turn_off:'关闭'})[action]||'控制设备'}
    async function controlEntity(s){try{const current=await api(`/api/states/${s.entity_id}`,{}),domain=s.entity_id.split('.')[0],action=controlAction(current);await api(`/api/services/${domain}/${action}`,{},{method:'POST',body:JSON.stringify({entity_id:s.entity_id})});$('#device-modal').classList.remove('show');await sync({});notice(`「${label(s)}」已${controlLabel(current)}`)}catch(err){notice(err.message)}}
    async function api(path,_cfg,options={}){if(!HA?.url||!HA?.token)throw new Error('Home Assistant 配置缺失，请检查 config.js');const headers={Authorization:'Bearer '+HA.token,...(options.headers||{})};if(options.body)headers['Content-Type']='application/json';const r=await fetch(HA.url.replace(/\/$/,'')+path,{...options,headers});if(!r.ok){const body=(await r.text()).replace(/\s+/g,' ').slice(0,500);throw new Error(`${options.method||'GET'} ${path} 返回 HTTP ${r.status}${body?`：${body}`:''}`)}try{return await r.json()}catch{throw new Error(`${options.method||'GET'} ${path} 返回了无法解析的 JSON 响应`)}}
    function registrySocketUrl(){const url=new URL(HA.url);url.protocol=url.protocol==='https:'?'wss:':'ws:';url.pathname=url.pathname.replace(/\/$/,'')+'/api/websocket';url.search='';url.hash='';return url.toString()}
    function registryCommand(type){return new Promise((resolve,reject)=>{const socket=new WebSocket(registrySocketUrl()),timer=setTimeout(()=>{socket.close();reject(new Error('区域注册表同步超时'))},10000);let settled=false;const fail=message=>{if(settled)return;settled=true;clearTimeout(timer);socket.close();reject(new Error(message))};socket.onmessage=event=>{try{const message=JSON.parse(event.data);if(message.type==='auth_required')socket.send(JSON.stringify({type:'auth',access_token:HA.token}));else if(message.type==='auth_invalid')fail('Home Assistant WebSocket 认证失败');else if(message.type==='auth_ok')socket.send(JSON.stringify({id:1,type}));else if(message.type==='result'&&message.id===1){if(settled)return;settled=true;clearTimeout(timer);socket.close();message.success?resolve(message.result):reject(new Error(message.error?.message||`${type} 读取失败`))}}catch(error){fail('Home Assistant WebSocket 返回了无效数据')}};socket.onerror=()=>fail('无法连接 Home Assistant WebSocket')})}
    async function syncRegistry(force=false){if(!force&&registrySyncedAt&&Date.now()-registrySyncedAt<5*60*1000)return registry;const [areas,devices,entities]=await Promise.all([registryCommand('config/area_registry/list'),registryCommand('config/device_registry/list'),registryCommand('config/entity_registry/list')]);registry={areas:Array.isArray(areas)?areas:[],devices:Array.isArray(devices)?devices:[],entities:Array.isArray(entities)?entities:[]};registrySyncedAt=Date.now();return registry}
    const escapeHtml=s=>String(s||'').replace(/[&<>'\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
    const TODO_ENTITY='todo.login_ren_wu';
    function agendaError(title,detail){$('#agenda-source').textContent='MS365 To Do 同步失败';$('#agenda-list').innerHTML=`<div class="agenda-row"><span class="agenda-time">!</span><div><div class="agenda-title">${escapeHtml(title)}</div><div class="agenda-meta">${escapeHtml(detail)}</div></div><span class="tag life">错误</span></div>`}
    function renderTodos(todos,listName){$('#agenda-list').innerHTML='';$('#agenda-source').textContent='MS365 To Do';if(!todos.length){$('#agenda-list').innerHTML='<div class="agenda-row"><span class="agenda-time">✓</span><div><div class="agenda-title">没有未完成任务</div><div class="agenda-meta">todo.login_ren_wu 已成功同步</div></div><span class="tag life">MS365 To Do</span></div>';return}$('#agenda-list').innerHTML=todos.slice(0,3).map(todo=>{const due=todo.due?.dateTime||todo.due||todo.due_date;let dueText='未设置截止日期';if(due){const d=new Date(due);dueText=Number.isNaN(d.getTime())?String(due):'截止 '+d.toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})}return `<div class="agenda-row"><span class="agenda-time">待办</span><div><div class="agenda-title">${escapeHtml(todo.subject||todo.summary||todo.title||'未命名任务')}</div><div class="agenda-meta">${escapeHtml(dueText)}</div></div><span class="tag life">${escapeHtml(listName)}</span></div>`}).join('')}
    async function syncTodo(states,cfg){const preferred=states.find(s=>s.entity_id===TODO_ENTITY);if(!preferred){const ids=states.filter(s=>s.entity_id.startsWith('todo.')).map(s=>s.entity_id).join(', ')||'未发现任何 todo.* 实体';agendaError(`找不到实体 ${TODO_ENTITY}`,`Home Assistant 当前待办实体：${ids}`);return}const listName=label(preferred),fromState=preferred.attributes.all_todos||preferred.attributes.items;if(Array.isArray(fromState)){renderTodos(fromState,listName);return}try{const result=await api('/api/services/todo/get_items?return_response',cfg,{method:'POST',body:JSON.stringify({entity_id:TODO_ENTITY,status:'needs_action'})});const data=result.service_response?.[TODO_ENTITY]||result[TODO_ENTITY]||{};if(!Array.isArray(data.items))throw new Error(`服务响应中未找到 ${TODO_ENTITY}.items：${JSON.stringify(result).slice(0,500)}`);renderTodos(data.items,listName)}catch(err){console.error('MS365 To Do 同步失败：',err);agendaError('无法读取 MS365 To Do 任务',err.message)}}
    function calendarFailure(error){
      const message=error?.message||String(error);
      const cors=/failed to fetch|cors|networkerror/i.test(message);
      $('#agenda-source').textContent=cors?'日历跨域未授权':'日历同步失败';
      $('#agenda-list').innerHTML=`<div class="agenda-row"><span class="agenda-time">!</span><div><div class="agenda-title">${cors?'无法读取 Home Assistant 日历':'日历暂时无法同步'}</div><div class="agenda-meta">${cors?'home.mcylyr.cn 的 OPTIONS 响应缺少 Access-Control-Allow-Origin；需在反向代理放行 life.mcylyr.cn':'请稍后刷新重试'}</div></div><span class="tag">日历</span></div>`;
      console.error('Home Assistant 日历同步失败：',error);
    }
    async function syncCalendar(states,cfg){try{const calendars=states.filter(s=>s.entity_id.startsWith('calendar.'));if(!calendars.length)return;const start=new Date(),end=new Date();start.setHours(0,0,0,0);end.setHours(23,59,59,999);const result=await api('/api/services/calendar/get_events?return_response',cfg,{method:'POST',body:JSON.stringify({entity_id:calendars.map(s=>s.entity_id),start_date_time:start.toISOString(),end_date_time:end.toISOString()})});const response=result.service_response||result;const events=calendars.flatMap(cal=>(response[cal.entity_id]?.events||[]).map(e=>({...e,calendar:label(cal)}))).sort((a,b)=>new Date(a.start.dateTime||a.start.date)-new Date(b.start.dateTime||b.start.date)).slice(0,4);if(!events.length)return;$('#agenda-source').textContent='Home Assistant 日历';$('#agenda-list').innerHTML=events.map(e=>{const allDay=!!e.start.date,time=allDay?'全天':new Date(e.start.dateTime).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});return `<div class="agenda-row"><span class="agenda-time">${time}</span><div><div class="agenda-title">${escapeHtml(e.summary)}</div><div class="agenda-meta">${escapeHtml(e.location||e.calendar)}</div></div><span class="tag">${escapeHtml(e.calendar)}</span></div>`}).join('')}catch(error){calendarFailure(error)}}
    async function sync(cfg){if(syncing)return;syncing=true;try{const states=await api('/api/states',cfg);latestStates=states;try{await syncRegistry()}catch(error){console.warn('Home Assistant 区域注册表同步失败，已降级为全部实体列表：',error)}const temp=environmentSensors(states,'temperature')[0]||entity(states,'sensor',['temperature','温度']),humidity=environmentSensors(states,'humidity')[0]||entity(states,'sensor',['humidity','湿度']);if(value(temp))$('#temperature').textContent=value(temp);$('#environment').textContent=[humidity&&value(humidity)?'湿度 '+value(humidity)+(humidity.attributes.unit_of_measurement||'%'):'已连接 Home Assistant','刚刚同步'].filter(Boolean).join(' · ');$('#ha-status').textContent=registry.areas.length?'实时同步 · 区域已连接':'实时同步';renderEnvironmentSlots(states);renderQuick(states);renderDevices(states);await syncCalendar(states,cfg).catch(()=>{});await syncTodo(states,cfg) }finally{syncing=false;$('#app-loader').classList.add('hidden')}}
    function beginAutoSync(cfg){if(syncTimer)clearInterval(syncTimer);syncTimer=setInterval(()=>sync(cfg).catch(()=>{$('#ha-status').textContent='同步失败'}),30000)}
    $('#connect-form').onsubmit=async e=>{
      e.preventDefault();
      if(!HA?.url||!HA?.token){notice('请先在 config.js 中填写 Home Assistant 地址和长期访问令牌');return}
      try{
        notice('正在连接…');
        await sync(HA);
        beginAutoSync(HA);
        hideModal();
        notice(`Home Assistant 已连接，读取到 ${latestStates.length} 个实体、${registry.areas.length} 个区域`)
      }catch(err){notice(err.message)}
    };
    loadRuntimeConfig().then(()=>{setLoginReady(true);return authenticate()}).then(ok=>{
      if(!ok)return;
      if(!HA?.url||!HA?.token){
        $('#ha-status').textContent='待连接';
        $('#environment').textContent='登录成功 · 请配置 Home Assistant';
        notice('登录成功，请先配置 Home Assistant');
        return;
      }
      sync(HA).then(()=>beginAutoSync(HA)).catch(()=>notice('Home Assistant 连接失败，请检查 config.js 与 CORS 设置'))
    }).catch(e=>{setLoginReady(false);loginError(e.message);$('#app-loader').classList.add('hidden')});
    document.querySelectorAll('.quick-grid button').forEach(b=>b.addEventListener('click',()=>{if(sessionStorage.getItem('life-hub-oidc'))return;b.classList.toggle('on');b.querySelector('small').textContent=b.classList.contains('on')?'已开启':'已关闭'}));
