const $=s=>document.querySelector(s), c=$('#clock'), modal=$('#connect-modal'), toast=$('#toast');
    const release=window.LIFE_HUB_RELEASE;
    const releaseLabel=release?.version?`v${release.version}${release.releasedAt?` · ${release.releasedAt}`:''}`:'版本信息缺失';
    document.querySelectorAll('[data-app-version]').forEach(element=>{element.textContent=releaseLabel});
    const projectUrl='https://github.com/Guyao146/Life-Dashboard';
    let OIDC=null;
    let LOCAL=null;
    const redirectUri=location.origin+location.pathname;
    let HA=null;
    const oidcSessionKey='life-hub-oidc';
    function ensureAdminStatus(){const card=$('#settings-connect')?.closest('.settings-card');if(!card)return null;let status=$('#admin-identity-status');if(!status){status=document.createElement('div');status.id='admin-identity-status';status.className='connection-note';card.querySelector('.settings-actions')?.before(status)}return status}
    function renderAdminStatus(config){const status=ensureAdminStatus();if(!status)return;const identity=config?.identity||{},auth=config?.authorization||{},groups=Array.isArray(auth.groups)?auth.groups:[],allowed=Array.isArray(auth.allowedGroups)?auth.allowedGroups:[];status.textContent=`OIDC：${identity.username||identity.email||'未识别账号'} · ${auth.administrator?'管理员已匹配':'非管理员'} · 当前组：${groups.join('、')||'未收到 groups 声明'} · 允许组：${allowed.join('、')||'未配置'}`}
    async function loadRuntimeConfig(){
      const response=await fetch('config.php?action=public',{cache:'no-store'}),config=await response.json();
      if(!response.ok||!config.ok)throw new Error(config.error||`公开配置接口返回 HTTP ${response.status}`);
      const missing=[];
      if(!config?.oidc?.clientId)missing.push('oidc.clientId');
      if(!config?.oidc?.authorize)missing.push('oidc.authorize');
      if(!config?.oidc?.token)missing.push('oidc.token');
      if(missing.length)throw new Error(`.env 公开配置缺失：${missing.join('、')}`);
      OIDC={...config.oidc};
      const localAuth=config.localAuth;
      LOCAL=localAuth?.username&&localAuth?.pbkdf2?.salt&&localAuth?.pbkdf2?.hash?{username:String(localAuth.username),pbkdf2:{salt:localAuth.pbkdf2.salt,hash:localAuth.pbkdf2.hash,iterations:Number(localAuth.pbkdf2.iterations)||310000}}:null;
    }
    async function loadPrivateRuntimeConfig(){
      const session=await validOidcSession(),token=session?.access_token;
      if(!token)throw new Error('只有 Authentik 管理员登录可以加载 Home Assistant 私密配置');
      const response=await oidcFetch('config.php?action=private',{cache:'no-store'}),config=await response.json();
      renderAdminStatus(config);
      if(!response.ok||!config.ok)throw new Error(config.error||`私密配置接口返回 HTTP ${response.status}`);
      if(!config?.homeAssistant?.url||!config?.homeAssistant?.token)throw new Error('.env 中缺少 Home Assistant 配置');
      HA={...config.homeAssistant,url:String(config.homeAssistant.url).replace(/\/$/,'')};
      return config.identity||null;
    }
    const b64url=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
    async function pkce(){const bytes=crypto.getRandomValues(new Uint8Array(48)),verifier=b64url(bytes),digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));return {verifier,challenge:b64url(digest)}}
    function loginError(m){$('#auth-error').textContent=m}
    function setLoginReady(ready){const button=$('#auth-login');button.disabled=!ready;if(ready&&$('#auth-error').textContent.includes('配置'))loginError('')}
    async function signIn(){
      if(!OIDC)throw new Error('登录配置尚未加载完成');
      if(!window.isSecureContext)throw new Error('Authentik 登录需要 HTTPS 部署（localhost 除外）');
      const {verifier,challenge}=await pkce(),state=b64url(crypto.getRandomValues(new Uint8Array(20)));
      sessionStorage.setItem('life-hub-pkce',JSON.stringify({verifier,state}));
      const p=new URLSearchParams({client_id:OIDC.clientId,response_type:'code',redirect_uri:redirectUri,scope:'openid profile email offline_access',state,code_challenge:challenge,code_challenge_method:'S256'});
      location.assign(OIDC.authorize+'?'+p)
    }
    /* ===== 静默 SSO：顶层 prompt=none 检测 Authentik 会话（Authentik 禁止 iframe 嵌入） ===== */
    const silentFlowKey='life-hub-silent-flow';
    function ssoStatus(){return $('#auth-sso')}
    function renderSsoIdentity(identity){const box=ssoStatus();if(!box)return;const name=identity?.username||identity?.email||'';if(!name){box.hidden=true;box.innerHTML='';return}box.hidden=false;box.innerHTML=`<button class="btn primary auth-sso-continue" id="auth-sso-continue" type="button"><span class="auth-sso-avatar">${escapeHtml(name.slice(0,1).toUpperCase())}</span><span class="auth-sso-copy"><small>检测到 樱落怡然验证服务 已登录</small><b>以 ${escapeHtml(name)} 的身份继续</b></span></button><button class="btn auth-sso-switch" id="auth-sso-switch" type="button">改用其他账号登录</button>`;$('#auth-sso-continue').onclick=()=>{loginError('');location.assign(redirectUri)};$('#auth-sso-switch').onclick=()=>{clearOidcSession();sessionStorage.setItem(silentFlowKey,'switched');box.hidden=true;box.innerHTML='';loginError('已切换为手动登录，请选择登录方式')}}
    async function trySilentSignIn(){
      if(!OIDC||!window.isSecureContext)return false;
      if(sessionStorage.getItem(silentFlowKey))return false;
      const {verifier,challenge}=await pkce(),state=b64url(crypto.getRandomValues(new Uint8Array(20)));
      sessionStorage.setItem('life-hub-pkce',JSON.stringify({verifier,state,silent:true}));
      sessionStorage.setItem(silentFlowKey,'pending');
      const p=new URLSearchParams({client_id:OIDC.clientId,response_type:'code',redirect_uri:redirectUri,scope:'openid profile email offline_access',state,prompt:'none',code_challenge:challenge,code_challenge_method:'S256'});
      location.assign(OIDC.authorize+'?'+p);
      return true
    }
    async function loadSsoIdentity(){try{const response=await oidcFetch('config.php?action=identity',{cache:'no-store'}),config=await response.json();return config?.identity||null}catch(error){return null}}
    function setLoaderStage(title='正在加载你的生活中枢',detail='正在准备安全连接…',stage=0){const loader=$('#app-loader');if(!loader)return;$('#loader-title').textContent=title;$('#loader-detail').textContent=detail;loader.dataset.stage=String(stage);loader.classList.remove('hidden');loader.setAttribute('aria-busy','true')}
    function finishDashboardLoad(){const loader=$('#app-loader');if(!loader)return;loader.setAttribute('aria-busy','false');loader.classList.add('hidden')}
    function enterDashboard(keepLoader=false){
      $('#auth-gate').classList.add('hidden');
      if(!keepLoader)finishDashboardLoad()
    }
    function readSession(key){try{return JSON.parse(sessionStorage.getItem(key)||'null')}catch(err){sessionStorage.removeItem(key);return null}}
    function readOidcSession(){try{const stored=JSON.parse(localStorage.getItem(oidcSessionKey)||'null');if(stored)return stored;const legacy=readSession(oidcSessionKey);if(legacy){localStorage.setItem(oidcSessionKey,JSON.stringify(legacy));sessionStorage.removeItem(oidcSessionKey)}return legacy}catch(err){localStorage.removeItem(oidcSessionKey);sessionStorage.removeItem(oidcSessionKey);return null}}
    function clearOidcSession(){localStorage.removeItem(oidcSessionKey);sessionStorage.removeItem(oidcSessionKey);sessionStorage.removeItem('life-hub-dashboard-access')}
    function saveOidcSession(tokens,previous=null){const now=Date.now(),rememberUntil=previous?.rememberUntil||now+(Number(OIDC?.rememberDays)||30)*86400000,next={...previous,...tokens,refresh_token:tokens.refresh_token||previous?.refresh_token||'',expiresAt:now+(Number(tokens.expires_in)||3600)*1000,rememberUntil};localStorage.setItem(oidcSessionKey,JSON.stringify(next));return next}
    let oidcRefreshPromise=null;
    async function performOidcRefresh(session){const latest=readOidcSession();if(!latest?.refresh_token||latest.rememberUntil<=Date.now())throw new Error('登录已过期');if(latest.refresh_token!==session.refresh_token||Number(latest.expiresAt)>Number(session.expiresAt))return latest;const form=new URLSearchParams({grant_type:'refresh_token',client_id:OIDC.clientId,refresh_token:latest.refresh_token});const response=await fetch(OIDC.token,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form});const tokens=await response.json().catch(()=>({}));if(!response.ok){const current=readOidcSession();if(current&&(current.refresh_token!==latest.refresh_token||Number(current.expiresAt)>Number(latest.expiresAt)))return current;throw new Error(tokens.error_description||tokens.error||'登录续期失败')}if(!tokens?.access_token)throw new Error('续期结果缺少 access_token');return saveOidcSession(tokens,latest)}
    async function refreshOidcSession(session){if(oidcRefreshPromise)return oidcRefreshPromise;const run=()=>performOidcRefresh(session);oidcRefreshPromise=(navigator.locks?.request?navigator.locks.request('life-hub-oidc-refresh',{mode:'exclusive'},run):run()).catch(error=>{const current=readOidcSession();if(current&&(current.refresh_token!==session.refresh_token||Number(current.expiresAt)>Number(session.expiresAt)))return current;clearOidcSession();throw error}).finally(()=>{oidcRefreshPromise=null});return oidcRefreshPromise}
    async function validOidcSession(forceRefresh=false){const session=readOidcSession();if(!session||session.rememberUntil<=Date.now()){clearOidcSession();return null}if(!forceRefresh&&session.access_token&&session.expiresAt>Date.now()+60000)return session;try{return await refreshOidcSession(session)}catch(error){return null}}
    function returnToLogin(message='登录已失效，请重新登录'){clearOidcSession();HA=null;if(workspaceTimer){clearInterval(workspaceTimer);workspaceTimer=0}if(syncTimer){clearInterval(syncTimer);syncTimer=null}$('#auth-gate').classList.remove('hidden');finishDashboardLoad();loginError(message);history.replaceState({},document.title,redirectUri)}
    async function oidcFetch(url,options={},retry=true){const session=await validOidcSession();if(!session){returnToLogin();throw new Error('登录已失效')}const headers={...(options.headers||{}),Authorization:'Bearer '+session.access_token},response=await fetch(url,{...options,headers});if(response.status===401&&retry){const refreshed=await validOidcSession(true);if(refreshed)return oidcFetch(url,options,false)}if(response.status===401){returnToLogin();throw new Error('登录已失效')}return response}
    async function authenticate(){
      const params=new URLSearchParams(location.search),stored=await validOidcSession();
      const silentPending=sessionStorage.getItem(silentFlowKey)==='pending';
      if(params.get('error')){
        const pending=readSession('life-hub-pkce');
        sessionStorage.removeItem('life-hub-pkce');
        history.replaceState({},document.title,redirectUri);
        if(silentPending||pending?.silent){
          // prompt=none 只是探测：未登录/需要交互时静默退回正常登录页。
          sessionStorage.setItem(silentFlowKey,'unavailable');
          $('#app-loader').classList.add('hidden');
          return false
        }
        throw new Error(`验证服务拒绝登录：${params.get('error_description')||params.get('error')}`);
      }
      if(stored?.access_token){
        setLoaderStage('正在恢复登录','正在安全验证你的登录状态…',1);enterDashboard(true);
        return true
      }
      if(!params.get('code')){
        const local=readSession('life-hub-local');
        if(stored?.access_token||local?.expiresAt>Date.now()){
          enterDashboard();
          return true
        }
        $('#app-loader').classList.add('hidden');
        return false
      }
      setLoaderStage('正在确认登录成功','正在与樱落怡然验证服务建立安全会话…',1);
      const pending=readSession('life-hub-pkce');
      if(!pending||pending.state!==params.get('state'))throw new Error('登录状态校验失败，请重新登录');
      const form=new URLSearchParams({grant_type:'authorization_code',client_id:OIDC.clientId,code:params.get('code'),redirect_uri:redirectUri,code_verifier:pending.verifier});
      const response=await fetch(OIDC.token,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form});
      if(!response.ok){sessionStorage.removeItem('life-hub-pkce');throw new Error('验证服务未接受登录请求，请检查回调地址、客户端类型和 CORS 设置')}
      const tokens=await response.json();
      if(!tokens?.access_token)throw new Error('验证服务返回的登录结果缺少 access_token');
      saveOidcSession(tokens);
      sessionStorage.removeItem('life-hub-pkce');
      sessionStorage.setItem(silentFlowKey,'done');
      history.replaceState({},document.title,redirectUri);
      if(pending.silent){
        // 静默探测成功：停在登录页展示“以 *** 的身份继续”，由用户确认后再进入看板。
        $('#app-loader').classList.add('hidden');
        renderSsoIdentity(await loadSsoIdentity());
        return false
      }
      setLoaderStage('登录成功','正在验证管理员权限…',2);enterDashboard(true);return true
    }
    $('#auth-login').onclick=()=>{
      loginError('正在跳转到 验证服务…');
      signIn().catch(e=>loginError(e.message))
    };
    $('#auth-continue')?.addEventListener('click',enterDashboard);
    function logout(){
      clearOidcSession();
      sessionStorage.removeItem('life-hub-pkce');
      sessionStorage.removeItem(localSessionKey);
      sessionStorage.removeItem(localFailsKey);
      sessionStorage.removeItem(localLockKey);
      location.assign(redirectUri)
    }
    $('#auth-logout').onclick=logout;
    const localSessionKey='life-hub-local',localFailsKey='life-hub-local-fails',localLockKey='life-hub-local-lock';
    function b64ToBytes(b64){const bin=atob(b64),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return bytes}
    async function deriveLocalHash(password,saltB64,iterations){
      const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);
      const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:b64ToBytes(saltB64),iterations},key,256);
      return btoa(String.fromCharCode(...new Uint8Array(bits)))
    }
    $('#auth-form').addEventListener('submit',async event=>{
      event.preventDefault();
      const submit=$('#auth-submit'),username=$('#auth-user').value.trim(),password=$('#auth-pass').value;
      loginError('');
      if(!LOCAL){loginError('本地账号未配置：请在服务器 .env 中填写本地登录信息');return}
      if(!window.isSecureContext){loginError('本地登录需要 HTTPS 部署（localhost 除外）');return}
      const lock=readSession(localLockKey);
      if(lock?.until>Date.now()){loginError(`尝试次数过多，请 ${Math.ceil((lock.until-Date.now())/1000)} 秒后重试`);return}
      submit.disabled=true;submit.textContent='正在验证…';
      try{
        const hash=await deriveLocalHash(password,LOCAL.pbkdf2.salt,LOCAL.pbkdf2.iterations);
        if(username!==LOCAL.username||hash!==LOCAL.pbkdf2.hash){
          const fails=(readSession(localFailsKey)||0)+1;
          if(fails>=5){sessionStorage.setItem(localLockKey,JSON.stringify({until:Date.now()+30000}));sessionStorage.removeItem(localFailsKey);loginError('账号或密码不正确，已连续失败 5 次，请 30 秒后重试')}
          else{sessionStorage.setItem(localFailsKey,String(fails));loginError('账号或密码不正确')}
          return
        }
        sessionStorage.removeItem(localFailsKey);
        sessionStorage.setItem(localSessionKey,JSON.stringify({username,expiresAt:Date.now()+12*60*60*1000}));
        enterDashboard()
      }catch(err){loginError(`本地登录失败：${err.message}`)}
      finally{submit.disabled=false;submit.textContent='登　录'}
    });
    const displayNameKey='life-hub-display-name',defaultDisplayName='Gu';
    let renderedDate='',renderedGreeting='';
    function displayName(){try{return (localStorage.getItem(displayNameKey)||defaultDisplayName).trim().slice(0,24)||defaultDisplayName}catch(err){return defaultDisplayName}}
    function greetingForHour(hour){if(hour<5)return '深夜好';if(hour<11)return '早上好';if(hour<13)return '中午好';if(hour<17)return '下午好';if(hour<19)return '傍晚好';if(hour<23)return '晚上好';return '深夜好'}
    function renderGreeting(d){const text=`${greetingForHour(d.getHours())}，${displayName()}`;if(text===renderedGreeting)return;renderedGreeting=text;$('#greeting').textContent=text}
    function renderLocalDate(d){
      const weekdays=['星期日','星期一','星期二','星期三','星期四','星期五','星期六'], shortDays=['日','一','二','三','四','五','六'];
      $('#today').textContent=`${d.getMonth()+1} 月 ${d.getDate()} 日，${weekdays[d.getDay()]}`;
      const eta=new Date(d.getTime()+40*60*1000);$('#delivery-eta').textContent=eta.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});
      const monday=new Date(d);monday.setHours(0,0,0,0);monday.setDate(d.getDate()-((d.getDay()+6)%7));
      $('#habit-grid').innerHTML=Array.from({length:7},(_,i)=>{const day=new Date(monday);day.setDate(monday.getDate()+i);return `<div class="day ${i<((d.getDay()+6)%7)?'done':''}">${shortDays[day.getDay()]}<b>${day.getDate()}</b><i class="check"></i></div>`}).join('');
      [...$('#energy-bars').querySelectorAll('em')].forEach((label,i)=>{const day=new Date(d);day.setDate(d.getDate()-(3-i));label.textContent=i===3?'今天':`周${shortDays[day.getDay()]}`});
    }
    function tick(){const d=new Date();c.textContent=d.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});renderGreeting(d);const dateKey=d.toDateString();if(dateKey!==renderedDate){renderedDate=dateKey;renderLocalDate(d)}} tick();setInterval(tick,1000);
    function notice(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)}
    const updateMessage=sessionStorage.getItem('life-hub-update-message');if(updateMessage){sessionStorage.removeItem('life-hub-update-message');setTimeout(()=>notice(updateMessage),700)}
    function showModal(){modal.classList.add('show')} function hideModal(){modal.classList.remove('show')}
    $('#settings-connect').onclick=showModal; $('#cancel-connect').onclick=hideModal;
    let dshPairingTimer=0;
    function resetDshPairing(message='仅 Authentik 管理员可以生成；验证码只可使用一次。'){clearInterval(dshPairingTimer);dshPairingTimer=0;const box=$('#dsh-pairing-code');if(box)box.hidden=true;const status=$('#dsh-pairing-status');if(status)status.textContent=message}
    function showDshPairing(code,expiresAt){const box=$('#dsh-pairing-code'),value=$('#dsh-pairing-value'),expiry=$('#dsh-pairing-expiry'),status=$('#dsh-pairing-status');if(!box||!value||!expiry)return;clearInterval(dshPairingTimer);value.textContent=code;box.hidden=false;const render=()=>{const left=Math.max(0,Number(expiresAt)*1000-Date.now()),seconds=Math.ceil(left/1000);if(seconds<=0){resetDshPairing('验证码已过期，请重新生成。');return}expiry.textContent=`有效期 ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`};render();dshPairingTimer=setInterval(render,1000);if(status)status.textContent='请在 DSH 的「活动统计 → 总设置」输入这 6 位验证码。'}
    $('#dsh-pairing-create')?.addEventListener('click',async()=>{const button=$('#dsh-pairing-create');button.disabled=true;button.textContent='正在生成…';try{const response=await oidcFetch('config.php?action=workspace-pair-create',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',cache:'no-store'}),data=await response.json();if(!response.ok||!data?.ok||!/^\d{6}$/.test(String(data.code||'')))throw new Error(data?.error||`HTTP ${response.status}`);showDshPairing(String(data.code),data.expiresAt);notice('已生成 DSH 六位配对码')}catch(error){resetDshPairing(`生成失败：${error.message}`);notice(`生成 DSH 配对码失败：${error.message}`)}finally{button.disabled=false;button.textContent='生成 DSH 配对码'}});
    $('#dsh-pairing-copy')?.addEventListener('click',async()=>{const code=$('#dsh-pairing-value')?.textContent||'';if(!/^\d{6}$/.test(code))return;try{await navigator.clipboard.writeText(code);notice('配对码已复制')}catch(error){notice(`配对码：${code}`)}});
    ensureAdminStatus().textContent='OIDC 管理员身份将在登录后检查';
    modal.addEventListener('click',e=>{if(e.target===modal)hideModal()});
    $('#quick-picker').onclick=()=>openPicker();$('#cancel-picker').onclick=()=>$('#picker-modal').classList.remove('show');$('#picker-modal').onclick=e=>{if(e.target===$('#picker-modal'))$('#picker-modal').classList.remove('show')};$('#save-picker').onclick=()=>{const ids=[...$('#picker-list').querySelectorAll('input:checked')].map(input=>input.value).slice(0,6);saveQuickIds(ids);renderQuick(latestStates);$('#picker-modal').classList.remove('show');notice('快捷控制已保存')};
    $('#close-detail').onclick=()=>$('#device-modal').classList.remove('show');$('#device-modal').onclick=e=>{if(e.target===$('#device-modal'))$('#device-modal').classList.remove('show')};$('#detail-control').onclick=()=>{if(selectedDetail)controlEntity(selectedDetail)};$('#device-search').oninput=()=>renderDevices(latestStates);
    const widgetKey='life-hub-widgets',layoutKey='life-hub-layout',settingsLayoutKey='life-hub-settings-layout',navKey='life-hub-hidden-nav',widgetNames={workspaces:'工作区动态',home:'家庭环境',weather:'天气与预报',delivery:'外卖配送',agenda:'今日日程',countdown:'纪念日与倒数',quick:'快捷控制',devices:'HA 区域与场景',habit:'本周习惯',energy:'能量使用'},settingsNames={widgets:'小组件',countdowns:'纪念日与倒数',navigation:'导航分类',profile:'个性化',appearance:'外观',weather:'天气与位置',ai:'AI 助手',account:'连接与账户',version:'版本与更新'},navNames={home:'我的家',schedule:'日程',orders:'消费与订单',health:'健康'};
    const viewMeta={overview:{eyebrow:'LIFE OVERVIEW',title:'总览',description:'在一个页面中查看今天最重要的生活信息。'},home:{eyebrow:'SMART HOME',title:'我的家',description:'查看家庭环境、设备状态与常用场景。'},schedule:{eyebrow:'DAILY PLAN',title:'日程',description:'集中查看今天的日历事件、任务与安排。'},orders:{eyebrow:'ORDERS & SPENDING',title:'消费与订单',description:'跟踪配送进度、消费记录与家庭能耗。'},health:{eyebrow:'WELLNESS',title:'健康',description:'记录习惯、状态与持续改善的生活目标。'},settings:{eyebrow:'CONTROL CENTER',title:'设置',description:'管理你在看板中显示的内容和连接。'}};
    let activeView='overview';
    const defaultOrder=Object.keys(widgetNames),defaultSizes={workspaces:'large',home:'medium',weather:'medium',delivery:'small',agenda:'medium',countdown:'small',quick:'small',devices:'large',habit:'medium',energy:'small'},settingsDefaultSizes={widgets:'medium',countdowns:'medium',navigation:'small',profile:'small',appearance:'small',weather:'small',ai:'large',account:'medium',version:'small'},sizeNames={small:'小',medium:'中',large:'大'};
    function hiddenWidgets(){try{const value=JSON.parse(localStorage.getItem(widgetKey)||'[]');return new Set(Array.isArray(value)?value:[])}catch(err){localStorage.removeItem(widgetKey);return new Set()}}
    function hiddenNavItems(){try{const value=JSON.parse(localStorage.getItem(navKey)||'[]');return new Set(Array.isArray(value)?value.filter(id=>navNames[id]):[])}catch(err){localStorage.removeItem(navKey);return new Set()}}
    function layout(){try{const saved=JSON.parse(localStorage.getItem(layoutKey)||'{}'),order=Array.isArray(saved.order)?saved.order.filter(id=>defaultOrder.includes(id)):[],sizes=saved.sizes&&typeof saved.sizes==='object'?saved.sizes:{};return {order:[...order,...defaultOrder.filter(id=>!order.includes(id))],sizes}}catch(err){localStorage.removeItem(layoutKey);return {order:defaultOrder.slice(),sizes:{}}}}
    function saveLayout(next){try{localStorage.setItem(layoutKey,JSON.stringify(next))}catch(err){notice('无法保存组件布局')}}
    const settingsDefaultOrder=Object.keys(settingsNames);
    function settingsLayout(){try{const saved=JSON.parse(localStorage.getItem(settingsLayoutKey)||'{}'),order=Array.isArray(saved.order)?saved.order.filter(id=>settingsDefaultOrder.includes(id)):[],sizes=saved.sizes&&typeof saved.sizes==='object'?saved.sizes:{};return {order:[...order,...settingsDefaultOrder.filter(id=>!order.includes(id))],sizes}}catch(err){localStorage.removeItem(settingsLayoutKey);return {order:settingsDefaultOrder.slice(),sizes:{}}}}
    function saveSettingsLayout(next){try{localStorage.setItem(settingsLayoutKey,JSON.stringify(next))}catch(err){notice('无法保存设置页布局')}}
    function prepareSettingsCards(){document.querySelectorAll('.settings-card').forEach((card,index)=>{const id=settingsDefaultOrder[index];if(id&&!card.dataset.settingId)card.dataset.settingId=id})}
    let settingsMasonryFrame=0;
    function fitSettingsMasonry(){settingsMasonryFrame=0;const root=$('.settings-grid');if(!root||!root.offsetWidth)return;const style=getComputedStyle(root),row=parseFloat(style.gridAutoRows)||4,gap=parseFloat(style.rowGap)||0;root.querySelectorAll('[data-setting-id]').forEach(card=>{const height=card.getBoundingClientRect().height,next=`span ${Math.max(1,Math.ceil((height+gap)/(row+gap)))}`;if(card.style.gridRowEnd!==next)card.style.gridRowEnd=next})}
    function scheduleSettingsMasonry(){cancelAnimationFrame(settingsMasonryFrame);settingsMasonryFrame=requestAnimationFrame(()=>requestAnimationFrame(fitSettingsMasonry))}
    function applySettingsLayout(){const root=$('.settings-grid'),current=settingsLayout();current.order.forEach(id=>{const card=root.querySelector(`[data-setting-id="${id}"]`);if(card)root.append(card)});root.querySelectorAll('[data-setting-id]').forEach(card=>{const size=current.sizes[card.dataset.settingId]||settingsDefaultSizes[card.dataset.settingId]||'medium';card.classList.remove('size-small','size-medium','size-large');card.classList.add('size-'+(sizeNames[size]?size:'medium'));updateCardDraggable(card)});refreshWidgetMenus();scheduleSettingsMasonry()}
    function currentWidgetSize(id){const saved=layout().sizes[id];return sizeNames[saved]?saved:(defaultSizes[id]||'medium')}
    function updateCardDraggable(card){if(!card)return;card.draggable=false;const handle=card.querySelector('.widget-drag-handle');if(handle)handle.draggable=window.innerWidth>900&&!card.querySelector('.widget-menu.is-open')}
    function widgetPopover(menu){return document.getElementById(menu.dataset.popoverId)}
    function closeWidgetMenus(except=null){document.querySelectorAll('.widget-menu.is-open').forEach(menu=>{if(menu===except)return;menu.classList.remove('is-open');widgetPopover(menu)?.classList.remove('is-open');menu.querySelector('.widget-menu-trigger').setAttribute('aria-expanded','false');updateCardDraggable(menu.closest('[data-widget-id],[data-setting-id]'))})}
    function refreshWidgetMenus(){document.querySelectorAll('.widget-menu').forEach(menu=>{const card=menu.closest('[data-widget-id],[data-setting-id]'),current=card.dataset.settingId?(settingsLayout().sizes[card.dataset.settingId]||settingsDefaultSizes[card.dataset.settingId]||'medium'):currentWidgetSize(card.dataset.widgetId);widgetPopover(menu)?.querySelectorAll('[data-widget-size]').forEach(button=>{const active=button.dataset.widgetSize===current;button.classList.toggle('active',active);button.setAttribute('aria-checked',String(active))})})}
    function positionWidgetMenu(menu){const trigger=menu.querySelector('.widget-menu-trigger'),popover=widgetPopover(menu);if(!popover)return;const rect=trigger.getBoundingClientRect(),width=window.innerWidth<=580?180:164,height=popover.offsetHeight||132;popover.style.left=Math.max(10,Math.min(window.innerWidth-width-10,rect.right-width))+'px';popover.style.top=(rect.bottom+8+height<=window.innerHeight?rect.bottom+8:Math.max(10,rect.top-height-8))+'px'}
    function setupWidgetMenus(){document.querySelectorAll('.grid>[data-widget-id]').forEach(card=>{if(card.querySelector('.widget-menu'))return;const id=card.dataset.widgetId,popoverId=`widget-size-menu-${id}`,handle=document.createElement('span');handle.className='widget-drag-handle';handle.setAttribute('role','img');handle.setAttribute('aria-label',`拖动${widgetNames[id]}组件`);handle.title='按住拖动组件';handle.innerHTML='<i></i><i></i><i></i><i></i><i></i><i></i>';const menu=document.createElement('div');menu.className='widget-menu';menu.dataset.popoverId=popoverId;menu.innerHTML=`<button class="widget-menu-trigger" type="button" title="调整组件尺寸" aria-label="调整${widgetNames[id]}尺寸" aria-haspopup="menu" aria-controls="${popoverId}" aria-expanded="false">⋮</button>`;const popover=document.createElement('div');popover.id=popoverId;popover.className='widget-menu-popover';popover.setAttribute('role','menu');popover.setAttribute('aria-label',`${widgetNames[id]}组件尺寸`);popover.innerHTML=Object.entries(sizeNames).map(([value,name])=>`<button type="button" role="menuitemradio" data-widget-size="${value}"><span class="size-preview size-${value}"></span><span>${name}卡</span><small>${value==='small'?'1 列':value==='medium'?'2 列':'3 列'}</small></button>`).join('');document.body.append(popover);menu.querySelector('.widget-menu-trigger').onclick=e=>{e.stopPropagation();const open=!menu.classList.contains('is-open');closeWidgetMenus(menu);menu.classList.toggle('is-open',open);popover.classList.toggle('is-open',open);e.currentTarget.setAttribute('aria-expanded',String(open));updateCardDraggable(card);if(open){refreshWidgetMenus();requestAnimationFrame(()=>positionWidgetMenu(menu))}};popover.querySelectorAll('[data-widget-size]').forEach(button=>button.onclick=e=>{e.stopPropagation();const next=layout();next.sizes[id]=button.dataset.widgetSize;saveLayout(next);applyLayout();closeWidgetMenus();if(activeView==='settings')renderWidgetSettings();notice(`${widgetNames[id]}已调整为${sizeNames[button.dataset.widgetSize]}卡`)});card.querySelector('.card-head').append(handle,menu);updateCardDraggable(card)});refreshWidgetMenus()}
    function setupSettingsMenus(){document.querySelectorAll('.settings-card[data-setting-id]').forEach(card=>{if(card.querySelector(':scope > .widget-menu'))return;const id=card.dataset.settingId,name=settingsNames[id],popoverId=`setting-size-menu-${id}`,handle=document.createElement('span');handle.className='widget-drag-handle';handle.setAttribute('role','img');handle.setAttribute('aria-label',`拖动${name}设置卡片`);handle.title='按住拖动设置卡片';handle.innerHTML='<i></i><i></i><i></i><i></i><i></i><i></i>';const menu=document.createElement('div');menu.className='widget-menu';menu.dataset.popoverId=popoverId;menu.innerHTML=`<button class="widget-menu-trigger" type="button" title="调整卡片尺寸" aria-label="调整${name}尺寸" aria-haspopup="menu" aria-controls="${popoverId}" aria-expanded="false">⋮</button>`;const popover=document.createElement('div');popover.id=popoverId;popover.className='widget-menu-popover';popover.setAttribute('role','menu');popover.innerHTML=Object.entries(sizeNames).map(([value,label])=>`<button type="button" role="menuitemradio" data-widget-size="${value}"><span class="size-preview size-${value}"></span><span>${label}卡</span><small>${value==='small'?'1 列':value==='medium'?'2 列':'3 列'}</small></button>`).join('');document.body.append(popover);menu.querySelector('button').onclick=e=>{e.stopPropagation();const open=!menu.classList.contains('is-open');closeWidgetMenus(menu);menu.classList.toggle('is-open',open);popover.classList.toggle('is-open',open);e.currentTarget.setAttribute('aria-expanded',String(open));updateCardDraggable(card);if(open){refreshWidgetMenus();requestAnimationFrame(()=>positionWidgetMenu(menu))}};popover.querySelectorAll('[data-widget-size]').forEach(button=>button.onclick=e=>{e.stopPropagation();const next=settingsLayout();next.sizes[id]=button.dataset.widgetSize;saveSettingsLayout(next);applySettingsLayout();closeWidgetMenus();notice(`${name}已调整为${sizeNames[button.dataset.widgetSize]}卡`)});card.append(handle,menu);updateCardDraggable(card)});refreshWidgetMenus()}
    function applyLayout(){const grid=$('.grid'),current=layout();current.order.forEach(id=>{const card=grid.querySelector(`[data-widget-id="${id}"]`);if(card)grid.append(card)});grid.querySelectorAll('[data-widget-id]').forEach(card=>{const size=current.sizes[card.dataset.widgetId]||defaultSizes[card.dataset.widgetId]||'medium';card.classList.remove('size-small','size-medium','size-large');card.classList.add('size-'+(sizeNames[size]?size:'medium'));updateCardDraggable(card)});refreshWidgetMenus()}
    function applyNavVisibility(){const hidden=hiddenNavItems();document.querySelectorAll('.sidebar .nav [data-view]').forEach(item=>item.classList.toggle('nav-item-hidden',hidden.has(item.dataset.view)))}
    function applyView(){const hidden=hiddenWidgets();applyLayout();applySettingsLayout();applyNavVisibility();document.querySelectorAll('.grid>[data-widget-id]').forEach(card=>{const inView=activeView==='overview'||card.dataset.views.split(' ').includes(activeView);card.classList.toggle('is-hidden',!inView||hidden.has(card.dataset.widgetId))});$('.grid').classList.toggle('is-hidden',activeView==='settings');$('.settings-page').classList.toggle('is-active',activeView==='settings')}
    function renderWidgetSettings(){const hidden=hiddenWidgets(),current=layout(),root=$('#widget-settings');root.innerHTML=current.order.map(id=>`<div class="widget-setting-row"><label class="widget-toggle"><span><b>${widgetNames[id]}</b><small>${hidden.has(id)?'已隐藏':'显示在看板中'}</small></span><input type="checkbox" value="${id}" ${hidden.has(id)?'':'checked'}><i></i></label><select class="widget-size" data-size-id="${id}" aria-label="${widgetNames[id]}尺寸">${Object.entries(sizeNames).map(([value,name])=>`<option value="${value}" ${(current.sizes[id]||defaultSizes[id]||'medium')===value?'selected':''}>${name}卡</option>`).join('')}</select></div>`).join('');root.querySelectorAll('input').forEach(input=>input.onchange=()=>{const before=new Map(visibleCards().map(card=>[card,card.getBoundingClientRect()])),next=hiddenWidgets();input.checked?next.delete(input.value):next.add(input.value);localStorage.setItem(widgetKey,JSON.stringify([...next]));renderWidgetSettings();applyView();animateViewChange(before)});root.querySelectorAll('.widget-size').forEach(select=>select.onchange=()=>{const next=layout();next.sizes[select.dataset.sizeId]=select.value;saveLayout(next);applyView();notice(`${widgetNames[select.dataset.sizeId]}已调整为${sizeNames[select.value]}卡`)})}
    function renderNavSettings(){const hidden=hiddenNavItems(),root=$('#nav-settings');root.innerHTML=Object.entries(navNames).map(([id,name])=>`<label class="widget-toggle"><span><b>${name}</b><small>${hidden.has(id)?'已从左侧隐藏':'显示在左侧导航'}</small></span><input type="checkbox" value="${id}" ${hidden.has(id)?'':'checked'}><i></i></label>`).join('');root.querySelectorAll('input').forEach(input=>input.onchange=()=>{const next=hiddenNavItems();input.checked?next.delete(input.value):next.add(input.value);localStorage.setItem(navKey,JSON.stringify([...next]));applyNavVisibility();renderNavSettings();notice(`${navNames[input.value]}已${input.checked?'显示':'隐藏'}`)})}
    function syncProfileSettings(){$('#profile-name').value=displayName()}
    function visibleCards(){return [...document.querySelectorAll('.grid>[data-widget-id]:not(.is-hidden)')]}
    function animateViewChange(before){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;requestAnimationFrame(()=>visibleCards().forEach((card,index)=>{if(typeof card.animate!=='function')return;const start=before.get(card);if(!start){card.animate([{transform:'translateY(18px) scale(.985)',opacity:0},{transform:'translateY(0) scale(1)',opacity:1}],{duration:380,delay:Math.min(index*35,175),easing:'cubic-bezier(.22,1,.36,1)',fill:'backwards'});return}const end=card.getBoundingClientRect(),dx=start.left-end.left,dy=start.top-end.top;if(Math.abs(dx)<1&&Math.abs(dy)<1)return;card.animate([{transform:`translate(${dx}px,${dy}px)`,opacity:.72},{transform:'translate(0, 0)',opacity:1}],{duration:380,easing:'cubic-bezier(.22,1,.36,1)'})}))}
    function animateSettingsView(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const page=$('.settings-page');if(typeof page.animate!=='function')return;page.animate([{transform:'translateY(14px)',opacity:0},{transform:'translateY(0)',opacity:1}],{duration:360,easing:'cubic-bezier(.22,1,.36,1)'});page.querySelectorAll('.settings-card').forEach((card,index)=>card.animate([{transform:'translateY(16px) scale(.99)',opacity:0},{transform:'translateY(0) scale(1)',opacity:1}],{duration:420,delay:70+index*45,easing:'cubic-bezier(.22,1,.36,1)',fill:'backwards'}))}
    function renderViewIntro(view,animate=true){const meta=viewMeta[view]||viewMeta.overview,elements=[$('#view-eyebrow'),$('#view-title'),$('#view-description')];elements[0].textContent=meta.eyebrow;elements[1].textContent=meta.title;elements[2].textContent=meta.description;if(!animate||matchMedia('(prefers-reduced-motion: reduce)').matches)return;elements.forEach((element,index)=>{if(typeof element.animate!=='function')return;element.getAnimations().forEach(animation=>animation.cancel());element.animate([{transform:'translateY(10px)',opacity:0,filter:'blur(3px)'},{transform:'translateY(0)',opacity:1,filter:'blur(0)'}],{duration:360,delay:index*48,easing:'cubic-bezier(.22,1,.36,1)',fill:'backwards'})})}
    function compareVersions(a,b){const parse=value=>{const match=String(value||'').trim().replace(/^v/i,'').match(/^(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.-]+))?/);if(!match)return null;return {parts:match.slice(1,4).map(Number),pre:match[4]||''}},left=parse(a),right=parse(b);if(!left||!right)return null;for(let i=0;i<3;i++){if(left.parts[i]!==right.parts[i])return left.parts[i]>right.parts[i]?1:-1}if(left.pre===right.pre)return 0;if(!left.pre)return 1;if(!right.pre)return -1;return left.pre.localeCompare(right.pre,undefined,{numeric:true,sensitivity:'base'})}
    let pendingRemoteVersion='';
    function setUpdateAvailable(version){pendingRemoteVersion=version||'';const dashboard=$('#upgrade-dashboard');if(dashboard)dashboard.href=pendingRemoteVersion?`upgrade.html?version=${encodeURIComponent(pendingRemoteVersion)}`:'upgrade.html'}
    let updateCheckPromise=null;
    function checkForUpdate(options={}){if(updateCheckPromise)return updateCheckPromise;updateCheckPromise=runUpdateCheck(options).finally(()=>{updateCheckPromise=null});return updateCheckPromise}
    async function runUpdateCheck(options={}){const status=$('#version-status'),button=$('#check-update');if(!status||!button)return null;button.disabled=true;if(!options.silent)status.textContent='正在检查远端版本…';try{const response=await fetch('update.php',{method:'POST',headers:{'X-Life-Hub-Update-Command':'check','Content-Type':'application/json'},body:'{}',cache:'no-store'});let data=null;try{data=await response.json()}catch(error){throw new Error(`版本接口返回 HTTP ${response.status}`)}if(!response.ok||!data.ok)throw new Error(data.error||`HTTP ${response.status}`);const remoteVersion=data.remoteVersion,localVersion=release?.version;if(!remoteVersion||!localVersion)throw new Error('版本格式无法识别');const comparison=compareVersions(remoteVersion,localVersion);if(comparison===null)throw new Error('版本号不是有效的语义化版本');if(comparison>0){setUpdateAvailable(remoteVersion);status.textContent=`发现新版本 v${remoteVersion}`;notice(`发现新版本 v${remoteVersion}，可在设置中升级`)}else if(comparison<0){setUpdateAvailable('');status.textContent=`本地 v${localVersion} 高于远程 v${remoteVersion}`;if(!options.silent)notice('当前部署版本高于远端版本')}else{setUpdateAvailable('');status.textContent='已是最新版本';if(!options.silent)notice('当前已经是最新版本')}return {remoteVersion,comparison}}catch(error){console.warn('版本检查失败：',error);if(!options.silent){status.textContent='检查失败，请稍后重试';notice(`版本检查失败：${error.message}`)}return null}finally{button.disabled=false}}
    async function requestUpdate(retry=true){const session=await validOidcSession();if(!session){returnToLogin();throw new Error('需要重新登录管理员账号')}const response=await fetch('update.php',{method:'POST',headers:{'X-Life-Hub-Update-Command':'update','Content-Type':'application/json'},body:JSON.stringify({version:pendingRemoteVersion,accessToken:session.access_token}),cache:'no-store'});let data=null;try{data=await response.json()}catch(error){throw new Error(`服务器返回 HTTP ${response.status}`)}if(response.status===401&&retry){const refreshed=await validOidcSession(true);if(refreshed)return requestUpdate(false);returnToLogin()}if(response.status===401){returnToLogin();throw new Error('登录已失效')}return {response,data}}
    function setView(view){if(view===activeView)return;const before=new Map(visibleCards().map(card=>[card,card.getBoundingClientRect()]));activeView=view;document.querySelectorAll('[data-view]').forEach(item=>{const isActive=item.dataset.view===view;item.classList.toggle('active',isActive);if(item.closest('.nav,.mobile-nav'))item.setAttribute('aria-current',isActive?'page':'false')});renderViewIntro(view);applyView();if(view==='settings'){renderWidgetSettings();renderNavSettings();syncProfileSettings();renderThemeSettings();renderCountdownSettings();syncWeatherSettings();syncAiSettings();requestAnimationFrame(animateSettingsView)}else animateViewChange(before);window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
    document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>setView(button.dataset.view));
    $('#profile-form').onsubmit=e=>{e.preventDefault();const name=$('#profile-name').value.trim().replace(/\s+/g,' ').slice(0,24);if(!name){notice('请输入你希望显示的称呼');$('#profile-name').focus();return}try{localStorage.setItem(displayNameKey,name)}catch(err){notice('浏览器阻止了称呼保存');return}$('#profile-name').value=name;renderedGreeting='';renderGreeting(new Date());notice('称呼已保存')};
    $('#settings-reset').onclick=()=>{localStorage.removeItem(widgetKey);localStorage.removeItem(layoutKey);localStorage.removeItem(settingsLayoutKey);localStorage.removeItem(navKey);localStorage.removeItem('life-hub-quick');localStorage.removeItem(environmentSlotsKey);renderWidgetSettings();renderNavSettings();renderEnvironmentSlots(latestStates);applySettingsLayout();setView('overview');notice('主页与设置页布局、小组件、导航和环境数据位已恢复默认')};
    const grid=$('.grid');let draggedCard=null;const reorderAnimations=new WeakMap();
    prepareSettingsCards();setupWidgetMenus();setupSettingsMenus();applySettingsLayout();
    if('ResizeObserver' in window){const settingsResizeObserver=new ResizeObserver(scheduleSettingsMasonry);settingsResizeObserver.observe($('.settings-grid'));document.querySelectorAll('.settings-card').forEach(card=>settingsResizeObserver.observe(card))}
    document.fonts?.ready.then(scheduleSettingsMasonry);
    document.addEventListener('click',()=>closeWidgetMenus());document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;closeWidgetMenus();closeEnvironmentPicker();closeWorkspaceDetail();closeAiPanel();$('#picker-modal').classList.remove('show');$('#device-modal').classList.remove('show')});window.addEventListener('resize',()=>{applyLayout();scheduleSettingsMasonry();closeWidgetMenus()});
    function animateCardReorder(target,before){const cards=[...grid.querySelectorAll('[data-widget-id]')],first=new Map(cards.map(card=>[card,card.getBoundingClientRect()])),reference=before?target:target.nextSibling;if(reference===draggedCard||draggedCard.nextSibling===reference)return;target.parentNode.insertBefore(draggedCard,reference);cards.forEach(card=>{if(card===draggedCard)return;const start=first.get(card),end=card.getBoundingClientRect(),dx=start.left-end.left,dy=start.top-end.top;if(Math.abs(dx)<1&&Math.abs(dy)<1)return;reorderAnimations.get(card)?.cancel();if(typeof card.animate!=='function')return;const animation=card.animate([{transform:`translate(${dx}px,${dy}px)`},{transform:'translate(0, 0)'}],{duration:190,easing:'cubic-bezier(.2,.8,.2,1)'});reorderAnimations.set(card,animation);animation.onfinish=()=>{if(reorderAnimations.get(card)===animation)reorderAnimations.delete(card)}})}
    function dragGhost(card){const ghost=document.createElement('div');ghost.className='widget-drag-ghost';ghost.textContent=card.querySelector('h2,h3')?.textContent||widgetNames[card.dataset.widgetId]||settingsNames[card.dataset.settingId]||'卡片';document.body.append(ghost);return ghost}
    grid.addEventListener('dragstart',e=>{const handle=e.target.closest('.widget-drag-handle'),card=handle?.closest('[data-widget-id]');if(!handle||!card||window.innerWidth<=900){e.preventDefault();return}closeWidgetMenus();draggedCard=card;const ghost=dragGhost(card);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',card.dataset.widgetId);e.dataTransfer.setDragImage(ghost,18,18);requestAnimationFrame(()=>{card.classList.add('is-dragging');ghost.remove()})});
    grid.addEventListener('dragover',e=>{const target=e.target.closest('[data-widget-id]');if(!draggedCard||!target||target===draggedCard)return;e.preventDefault();e.dataTransfer.dropEffect='move';const rect=target.getBoundingClientRect(),before=Math.abs(e.clientY-(rect.top+rect.height/2))>rect.height*.25?e.clientY<rect.top+rect.height/2:e.clientX<rect.left+rect.width/2;animateCardReorder(target,before)});
    grid.addEventListener('dragend',()=>{if(!draggedCard)return;draggedCard.classList.remove('is-dragging');saveLayout({...layout(),order:[...grid.querySelectorAll('[data-widget-id]')].map(card=>card.dataset.widgetId)});draggedCard=null;notice('组件位置已保存')});
    const settingsGrid=$('.settings-grid');let draggedSetting=null;
    settingsGrid.addEventListener('dragstart',e=>{const handle=e.target.closest('.widget-drag-handle'),card=handle?.closest('[data-setting-id]');if(!handle||!card||window.innerWidth<=900){e.preventDefault();return}closeWidgetMenus();draggedSetting=card;const ghost=dragGhost(card);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',card.dataset.settingId);e.dataTransfer.setDragImage(ghost,18,18);requestAnimationFrame(()=>{card.classList.add('is-dragging');ghost.remove()})});
    settingsGrid.addEventListener('dragover',e=>{const target=e.target.closest('[data-setting-id]');if(!draggedSetting||!target||target===draggedSetting)return;e.preventDefault();const rect=target.getBoundingClientRect(),before=e.clientY<rect.top+rect.height/2;target.parentNode.insertBefore(draggedSetting,before?target:target.nextSibling)});
    settingsGrid.addEventListener('dragend',()=>{if(!draggedSetting)return;draggedSetting.classList.remove('is-dragging');saveSettingsLayout({...settingsLayout(),order:[...settingsGrid.querySelectorAll('[data-setting-id]')].map(card=>card.dataset.settingId)});draggedSetting=null;scheduleSettingsMasonry();notice('设置卡片位置已保存')});
    $('#settings-logout').onclick=logout;
    $('#check-update').onclick=()=>checkForUpdate();
    applyView();
    checkForUpdate({silent:true});
    $('#refresh-home').onclick=()=>{registrySyncedAt=0;return sync({}).then(()=>notice('已刷新 Home Assistant 数据')).catch(err=>notice(err.message))};
    document.querySelectorAll('.more:not(#refresh-home):not(#quick-picker):not(#close-detail):not(#close-environment-picker):not(#close-workspace-detail):not(#ai-close)').forEach(button=>button.onclick=()=>notice('该数据源尚未接入，可继续扩展'));
    let syncTimer=null, syncing=false, latestStates=[], selectedDetail=null,activeEnvironmentSlot=0,registry={areas:[],devices:[],entities:[]},registrySyncedAt=0;
    const environmentSlotsKey='life-hub-environment-slots';
    const controllableDomains=['light','switch','fan','climate','vacuum','cover','media_player','lock','input_boolean','button','input_button','script','automation','siren','humidifier','water_heater'];
    const deviceGroups={light:['灯光','☼'],switch:['开关','⏻'],fan:['风扇','◉'],climate:['空调与温控','♨'],vacuum:['清洁设备','◔'],cover:['窗帘与遮阳','▤'],media_player:['媒体设备','♬'],lock:['门锁','⌑'],input_boolean:['虚拟开关','◌'],button:['按钮','●'],input_button:['按钮','●'],script:['脚本','▷'],automation:['自动化','↻'],siren:['警报器','!'],humidifier:['加湿器','≈'],water_heater:['热水器','♨']};
    const canControl=s=>Boolean(s?.entity_id)&&controllableDomains.includes(s.entity_id.split('.')[0])&&!['unknown','unavailable'].includes(s.state);
    function entity(states, domain, words=[]){return states.find(s=>s.entity_id.startsWith(domain+'.') && (words.length===0||words.some(w=>(s.attributes.friendly_name||s.entity_id).toLowerCase().includes(w))))}
    function value(s){return s?.state && !['unknown','unavailable'].includes(s.state) ? s.state : null}
    function label(s){return s.attributes.friendly_name||s.entity_id.split('.').pop().replaceAll('_',' ')}
    function environmentSensorKind(s){
      if(!s?.entity_id?.startsWith('sensor.'))return null;
      const deviceClass=String(s.attributes?.device_class||'').toLowerCase(),unit=String(s.attributes?.unit_of_measurement||'').trim().toLowerCase(),name=`${s.entity_id} ${s.attributes?.friendly_name||''}`.toLowerCase();
      if(deviceClass==='temperature'||/温度|temperature|temp/.test(name)||['°c','℃','°f'].includes(unit))return 'temperature';
      if(deviceClass==='humidity'||/湿度|humidity/.test(name))return 'humidity';
      return null
    }
    function environmentSensors(states,kind=null){return (Array.isArray(states)?states:[]).filter(s=>{const detected=environmentSensorKind(s);return detected&&(!kind||detected===kind)}).sort((a,b)=>label(a).localeCompare(label(b),'zh-CN'))}
    function savedEnvironmentIds(){try{const ids=JSON.parse(localStorage.getItem(environmentSlotsKey)||'[]');return Array.from({length:2},(_,index)=>Array.isArray(ids)&&typeof ids[index]==='string'?ids[index]:'')}catch(err){localStorage.removeItem(environmentSlotsKey);return ['','']}}
    function saveEnvironmentIds(ids){try{localStorage.setItem(environmentSlotsKey,JSON.stringify(Array.from({length:2},(_,index)=>ids[index]||'')))}catch(err){notice('浏览器阻止了环境传感器选择保存')}}
    function defaultEnvironmentIds(states){const temperature=environmentSensors(states,'temperature')[0]?.entity_id||'',humidity=environmentSensors(states,'humidity')[0]?.entity_id||'',all=environmentSensors(states);return [temperature||all[0]?.entity_id||'',humidity||all[1]?.entity_id||all[0]?.entity_id||'']}
    function resolvedEnvironmentIds(states){const saved=savedEnvironmentIds(),defaults=defaultEnvironmentIds(states),resolved=saved.map((id,index)=>id||defaults[index]);if(resolved.some((id,index)=>id!==saved[index]))saveEnvironmentIds(resolved);return resolved}
    function environmentSensorValue(s){const current=value(s);if(current===null)return '不可用';const unit=s.attributes?.unit_of_measurement||({temperature:'°C',humidity:'%'})[environmentSensorKind(s)]||'';return `${current}${unit}`}
    function renderEnvironmentSlots(states){const safeStates=Array.isArray(states)?states:[],ids=resolvedEnvironmentIds(safeStates);document.querySelectorAll('[data-environment-slot]').forEach((button,index)=>{const sensor=safeStates.find(s=>s.entity_id===ids[index]),name=button.querySelector('span'),reading=button.querySelector('strong');name.textContent=sensor?label(sensor):`环境数据 ${index+1}`;reading.textContent=sensor?environmentSensorValue(sensor):'点击选择';button.title=sensor?`${sensor.entity_id} · 点击更换`:`选择第 ${index+1} 个环境传感器`;button.setAttribute('aria-label',button.title)})}
    function environmentSensorOption(s,selectedId){const area=entityArea(s),meta=[area?.name,s.entity_id].filter(Boolean).join(' · ');return `<label class="environment-sensor-option"><input type="radio" name="environment-sensor" value="${escapeHtml(s.entity_id)}" ${s.entity_id===selectedId?'checked':''}><span class="environment-sensor-copy"><b>${escapeHtml(label(s))}</b><small title="${escapeHtml(meta)}">${escapeHtml(meta)}</small></span><span class="environment-sensor-value">${escapeHtml(environmentSensorValue(s))}</span></label>`}
    function renderEnvironmentSensorGroup(kind,title,icon,selectedId){const sensors=environmentSensors(latestStates,kind);return `<section class="environment-sensor-group"><h3><span>${icon}</span>${title}<small>${sensors.length} 个</small></h3><div class="environment-sensor-options">${sensors.length?sensors.map(s=>environmentSensorOption(s,selectedId)).join(''):`<div class="environment-sensor-empty">未发现${title}实体</div>`}</div></section>`}
    function closeEnvironmentPicker(){$('#environment-picker-modal').classList.remove('show')}
    function openEnvironmentPicker(index){activeEnvironmentSlot=Number(index)||0;const selectedId=resolvedEnvironmentIds(latestStates)[activeEnvironmentSlot];$('#environment-slot-kicker').textContent=`环境数据 ${activeEnvironmentSlot+1}`;$('#environment-picker-list').innerHTML=renderEnvironmentSensorGroup('temperature','温度','◒',selectedId)+renderEnvironmentSensorGroup('humidity','湿度','≈',selectedId);$('#environment-picker-modal').classList.add('show')}
    function quickIds(){try{const ids=JSON.parse(localStorage.getItem('life-hub-quick')||'[]');return Array.isArray(ids)?ids:[]}catch(err){localStorage.removeItem('life-hub-quick');return []}}
    function saveQuickIds(ids){try{localStorage.setItem('life-hub-quick',JSON.stringify(ids))}catch(err){notice('无法保存快捷设备，但本次选择仍可使用')}}
    function sceneLabel(s){return label(s).replace(/场景$/,'').trim()||label(s)}
    function isActive(s){return !['off','closed','locked','idle','docked','standby','paused','unknown','unavailable'].includes(String(s?.state).toLowerCase())}
    function entityIcon(s){return s.entity_id.startsWith('scene.')?'✦':(deviceGroups[s.entity_id.split('.')[0]]||['','◉'])[1]}
    function renderQuick(states){const safeStates=Array.isArray(states)?states:[],eligible=safeStates.filter(canControl);let ids=quickIds().filter(id=>eligible.some(s=>s.entity_id===id));if(!ids.length)ids=eligible.slice(0,4).map(s=>s.entity_id);const chosen=ids.map(id=>safeStates.find(s=>s.entity_id===id)).filter(Boolean),grid=$('#quick-grid');grid.innerHTML='';if(!chosen.length){grid.innerHTML='<div class="empty-picker">未发现可控设备，请检查 Home Assistant 实体状态。</div>';return}chosen.forEach(s=>grid.append(makeQuick(s)))}
    function entityArea(s){const entry=registry.entities.find(item=>item.entity_id===s.entity_id),device=entry?.device_id?registry.devices.find(item=>item.id===entry.device_id):null,areaId=entry?.area_id||device?.area_id||null;return areaId?registry.areas.find(item=>item.area_id===areaId||item.id===areaId):null}
    function appendEntityButton(root,s){const button=document.createElement('button');button.type='button';if(s.entity_id.startsWith('scene.')){button.className='device-item scene-item';button.innerHTML=`<span class="scene-icon">✦</span><span class="scene-copy"><strong>${escapeHtml(sceneLabel(s))}</strong><small>${escapeHtml(s.entity_id)}</small></span><span class="scene-action">执行</span>`;button.onclick=()=>runScene(s)}else{button.className='device-item';button.innerHTML=`<strong>${escapeHtml(label(s))}</strong><small class="${isActive(s)?'state-on':''}">${escapeHtml(s.state)} · ${escapeHtml(s.entity_id)}</small>`;button.onclick=()=>openDevice(s)}root.append(button)}
    function renderDevices(states){const safeStates=Array.isArray(states)?states:[],query=$('#device-search').value.trim().toLowerCase(),list=$('#device-list'),scenes=safeStates.filter(s=>s.entity_id.startsWith('scene.')),nonScenes=safeStates.filter(s=>!s.entity_id.startsWith('scene.')),groups=[];if(scenes.length)groups.push({id:'scenes',name:'场景',icon:'✦',items:scenes});registry.areas.slice().sort((a,b)=>String(a.name).localeCompare(String(b.name),'zh-CN')).forEach(area=>groups.push({id:area.area_id||area.id,name:area.name,icon:'⌂',items:nonScenes.filter(s=>(entityArea(s)?.area_id||entityArea(s)?.id)===(area.area_id||area.id))}));const assigned=new Set(groups.flatMap(group=>group.items.map(s=>s.entity_id))),unassigned=nonScenes.filter(s=>!assigned.has(s.entity_id));if(unassigned.length)groups.push({id:'unassigned',name:registry.areas.length?'未分配区域':'全部实体（区域信息未加载）',icon:'◉',items:unassigned});const filtered=groups.map(group=>{const areaMatch=group.name.toLowerCase().includes(query);return {...group,items:areaMatch?group.items:group.items.filter(s=>(`${label(s)} ${s.entity_id} ${s.state}`).toLowerCase().includes(query))}}).filter(group=>group.items.length||(!query&&group.id!=='unassigned'));$('#device-count').textContent=`${safeStates.length} 个实体 · ${registry.areas.length} 个区域 · ${scenes.length} 个场景`;list.innerHTML='';if(!filtered.length){list.innerHTML='<div class="empty-picker">没有匹配的区域、设备或场景。</div>';return}filtered.forEach(group=>{const details=document.createElement('details');details.className='device-group ha-device-group';details.open=Boolean(query)||group.id==='scenes';details.innerHTML=`<summary><span class="device-group-icon">${group.icon}</span><span>${escapeHtml(group.name)}</span><small>${group.items.length} 个实体</small></summary><div class="device-items"></div>`;group.items.forEach(s=>appendEntityButton(details.querySelector('.device-items'),s));list.append(details)})}
    function openDevice(s){selectedDetail=s;const area=entityArea(s);$('#detail-name').textContent=label(s);$('#detail-state').textContent=s.state;const attrs=[...(area?[['区域',area.name]]:[]),...Object.entries(s.attributes||{}).filter(([k])=>k!=='friendly_name').slice(0,19)];$('#detail-attrs').innerHTML=attrs.map(([k,v])=>`<div><span>${escapeHtml(k)}</span><b>${escapeHtml(typeof v==='object'?JSON.stringify(v):v)}</b></div>`).join('')||'<div><span>没有额外属性</span></div>';$('#detail-control').textContent=controlLabel(s);$('#detail-control').style.display=canControl(s)?'inline-block':'none';$('#device-modal').classList.add('show')}
    function updatePickerCount(){const inputs=[...$('#picker-list').querySelectorAll('input:checked')];$('#picker-count').textContent=`${inputs.length} / 6`;return inputs.length}
    function openPicker(){const selected=new Set(quickIds()),list=$('#picker-list'),groups=new Map();latestStates.filter(canControl).forEach(s=>{const domain=s.entity_id.split('.')[0];if(!groups.has(domain))groups.set(domain,[]);groups.get(domain).push(s)});list.innerHTML='';if(!groups.size)list.innerHTML='<div class="empty-picker">暂无可添加的可控设备，请先连接 Home Assistant。</div>';groups.forEach((states,domain)=>{const [name,icon]=deviceGroups[domain]||['其他设备','◉'],details=document.createElement('details');details.className='device-group';details.open=states.some(s=>selected.has(s.entity_id));details.innerHTML=`<summary><span class="device-group-icon">${icon}</span><span>${name}</span><small>${states.length} 个设备</small></summary><div class="picker-options">${states.map(s=>`<label class="picker-option"><input type="checkbox" value="${escapeHtml(s.entity_id)}" ${selected.has(s.entity_id)?'checked':''}><span title="${escapeHtml(s.entity_id)}">${escapeHtml(label(s))}</span></label>`).join('')}</div>`;list.append(details)});list.querySelectorAll('input').forEach(input=>input.onchange=()=>{if(updatePickerCount()>6){input.checked=false;updatePickerCount();notice('快捷控制最多选择 6 个设备')}});updatePickerCount();$('#picker-modal').classList.add('show')}
    document.querySelectorAll('[data-environment-slot]').forEach(button=>button.onclick=()=>openEnvironmentPicker(button.dataset.environmentSlot));
    $('#close-environment-picker').onclick=closeEnvironmentPicker;
    $('#cancel-environment-picker').onclick=closeEnvironmentPicker;
    $('#environment-picker-modal').onclick=e=>{if(e.target===$('#environment-picker-modal'))closeEnvironmentPicker()};
    $('#save-environment-picker').onclick=()=>{const selected=$('#environment-picker-list input[name="environment-sensor"]:checked');if(!selected){notice('请先选择一个温度或湿度传感器');return}const ids=savedEnvironmentIds();ids[activeEnvironmentSlot]=selected.value;saveEnvironmentIds(ids);renderEnvironmentSlots(latestStates);closeEnvironmentPicker();notice(`环境数据 ${activeEnvironmentSlot+1} 已保存`)};
    function makeQuick(s){const active=isActive(s),b=document.createElement('button');b.className=active?'on':'';b.innerHTML=`<span class="qicon">${entityIcon(s)}</span><span class="qname">${escapeHtml(label(s))}</span><small>${['button','input_button','script'].includes(s.entity_id.split('.')[0])?'点击执行':active?'已开启':'已关闭'}</small>`;b.onclick=()=>controlEntity(s);return b}
    async function runScene(scene){try{await api('/api/services/scene/turn_on',{}, {method:'POST',body:JSON.stringify({entity_id:scene.entity_id})});notice(`已执行「${sceneLabel(scene)}」`)}catch(err){notice(err.message)}}
    function controlAction(s){const domain=s.entity_id.split('.')[0],active=isActive(s);if(domain==='cover')return active?'close_cover':'open_cover';if(domain==='lock')return s.state==='unlocked'?'lock':'unlock';if(domain==='vacuum')return ['cleaning','returning'].includes(s.state)?'return_to_base':'start';if(['button','input_button'].includes(domain))return 'press';if(domain==='script')return 'turn_on';return active?'turn_off':'turn_on'}
    function controlLabel(s){const action=controlAction(s);return ({close_cover:'关闭',open_cover:'打开',lock:'上锁',unlock:'解锁',return_to_base:'返回充电',start:'启动',press:'按下',turn_on:'开启',turn_off:'关闭'})[action]||'控制设备'}
    async function controlEntity(s){try{const current=await api(`/api/states/${s.entity_id}`,{}),domain=s.entity_id.split('.')[0],action=controlAction(current);await api(`/api/services/${domain}/${action}`,{},{method:'POST',body:JSON.stringify({entity_id:s.entity_id})});$('#device-modal').classList.remove('show');await sync({});notice(`「${label(s)}」已${controlLabel(current)}`)}catch(err){notice(err.message)}}

    /* ===== DSH 工作区动态：Authentik 管理员同源代理 ===== */
    const workspaceStateMeta={completed:{label:'\u5df2\u5b8c\u6210',hint:'\u5f53\u524d\u56de\u5408\u5df2\u6b63\u5e38\u7ed3\u675f'},error:{label:'\u9047\u5230\u9519\u8bef',hint:'\u6700\u65b0\u64cd\u4f5c\u8fd4\u56de\u9519\u8bef'},choice:{label:'\u9700\u8981\u9009\u62e9',hint:'\u6b63\u5728\u7b49\u5f85\u4f60\u7684\u6279\u51c6\u6216\u9009\u62e9'},task:{label:'\u6b63\u5728\u8fdb\u884c\u4efb\u52a1',hint:'DSH \u6b63\u5728\u5904\u7406\u4efb\u52a1'},sleep:{label:'\u4f11\u7720\u4e2d',hint:'\u6682\u65f6\u6ca1\u6709\u8fdb\u884c\u4e2d\u7684\u4efb\u52a1'}};
    let workspaceSnapshot=null,workspaceTimer=0,workspaceSyncing=false;
    let selectedWorkspace=null,selectedWorkspaceSession=null;
    function compactNumber(value){const n=Number(value)||0;if(n>=1e9)return (n/1e9).toFixed(2)+'B';if(n>=1e6)return (n/1e6).toFixed(2)+'M';if(n>=1e3)return (n/1e3).toFixed(1)+'k';return String(n)}
    function relativeActivity(ageMs){if(ageMs===null||ageMs===undefined)return '\u6682\u65e0\u6d3b\u52a8';const seconds=Math.max(0,Math.floor(Number(ageMs)/1000));if(seconds<10)return '\u521a\u521a';if(seconds<60)return `${seconds} \u79d2\u524d`;const minutes=Math.floor(seconds/60);if(minutes<60)return `${minutes} \u5206\u949f\u524d`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours} \u5c0f\u65f6\u524d`;return `${Math.floor(hours/24)} \u5929\u524d`}
    function workspaceState(state){return workspaceStateMeta[state]||workspaceStateMeta.sleep}
    function workspaceLamp(state,extra=''){const meta=workspaceState(state);return `<i class="workspace-dot state-${escapeHtml(state||'sleep')} ${extra}" title="${escapeHtml(meta.hint)}" aria-label="${escapeHtml(meta.label)}"></i>`}
    function workspaceSessionText(item){const latest=item.latestSession||{},meta=workspaceState(latest.state||item.state);return latest.id?`${meta.label} · \u6700\u8fd1\u4f1a\u8bdd ${latest.id}${latest.turns?` · ${latest.turns} \u8f6e`:''}`:meta.label}
    function renderWorkspaces(data){
      workspaceSnapshot=data;
      const summary=data?.summary||{},items=Array.isArray(data?.workspaces)?data.workspaces:[],source=data?.source||{},root=$('#workspace-list'),status=$('#workspace-status');
      status.textContent=source.online?`${items.length} \u4e2a\u5de5\u4f5c\u533a · \u8f93\u51fa\u6bcf 10 \u79d2\u5237\u65b0`:`\u672c\u5730 DSH \u79bb\u7ebf${source.ageMs===null?'':` · ${relativeActivity(source.ageMs)}`}`;
      status.classList.toggle('workspace-source-offline',!source.online);
      const counters=$('#workspace-summary')?.querySelectorAll('b');if(counters?.length>=3){counters[0].textContent=summary.task||0;counters[1].textContent=summary.error||0;counters[2].textContent=summary.choice||0}
      if(!items.length){root.innerHTML=`<div class="empty-picker">${source.online?'DSH \u4e2d\u8fd8\u6ca1\u6709\u53ef\u663e\u793a\u7684\u5de5\u4f5c\u533a\u6d3b\u52a8。':'\u5c1a\u672a\u6536\u5230\u672c\u5730 DSH \u63a8\u9001；\u8bf7\u786e\u8ba4\u672c\u5730\u63d2\u4ef6\u3001\u63a8\u9001\u5730\u5740\u548c\u8fdc\u7aef\u5bc6\u94a5\u914d\u7f6e。'}</div>`;return}
      root.innerHTML=items.map((item,index)=>{const meta=workspaceState(item.state),sessions=Array.isArray(item.detailSessions)?item.detailSessions:[],sessionRows=item.detailAuthorized?(sessions.length?sessions.slice(0,5).map(session=>`<button class="workspace-session-preview" type="button" data-workspace-key="${escapeHtml(item.key)}" data-workspace-session="${escapeHtml(session.id)}">${workspaceLamp(session.state)}<span>${escapeHtml(session.title||'\u672a\u547d\u540d\u4f1a\u8bdd')}</span><small>${escapeHtml(workspaceState(session.state).label)} · ${relativeActivity(item.lastAt-(session.lastAt||item.lastAt))}</small></button>`).join(''):'<div class="workspace-session-empty">\u8be5\u5de5\u4f5c\u533a\u6682\u65e0\u4f1a\u8bdd\u8f93\u51fa。</div>'):'<div class="workspace-session-empty">\u672c\u673a\u672a\u6388\u6743\u4f20\u8f93\u4f1a\u8bdd\u4e0e\u8f93\u51fa。</div>';return `<details class="workspace-row state-${escapeHtml(item.state||'sleep')}" data-workspace-key="${escapeHtml(item.key)}" ${index===0&&item.state==='task'?'open':''}><summary>${workspaceLamp(item.state)}<span class="workspace-copy"><b>${escapeHtml(item.name||'\u672a\u547d\u540d\u5de5\u4f5c\u533a')}</b><small>${escapeHtml(workspaceSessionText(item))}</small></span><span class="workspace-state">${escapeHtml(meta.label)}</span><time>${relativeActivity(item.ageMs)}</time></summary><div class="workspace-detail"><span>\u8fd1 15 \u5206\u949f <b>${compactNumber(item.activeEvents)}</b> \u4e2a\u4e8b\u4ef6</span><span>\u4eca\u65e5\u6d3b\u52a8 <b>${compactNumber(item.todayEvents)}</b></span><span>\u4eca\u65e5 Token <b>${compactNumber(item.todayTokens)}</b></span><span>\u4f1a\u8bdd <b>${compactNumber(item.sessions)}</b></span></div><div class="workspace-session-preview-list">${sessionRows}</div><button class="btn workspace-open-detail" type="button">\u67e5\u770b\u5b9e\u65f6\u8f93\u51fa</button></details>`}).join('');
      root.querySelectorAll('.workspace-open-detail').forEach(button=>button.onclick=event=>{event.preventDefault();event.stopPropagation();const key=button.closest('[data-workspace-key]')?.dataset.workspaceKey,item=items.find(candidate=>candidate.key===key);if(item)openWorkspaceDetail(item)});
      root.querySelectorAll('[data-workspace-session]').forEach(button=>button.onclick=event=>{event.preventDefault();event.stopPropagation();const item=items.find(candidate=>candidate.key===button.dataset.workspaceKey),session=item?.detailSessions?.find(candidate=>candidate.id===button.dataset.workspaceSession);if(item&&session)openWorkspaceDetail(item,session.id)});
      const refreshed=items.find(item=>item.key===selectedWorkspace?.key);if(refreshed&&$('#workspace-detail-modal').classList.contains('show'))openWorkspaceDetail(refreshed,selectedWorkspaceSession?.id||'');
    }
    function workspaceRecordLabel(record){return ({user:'\u4f60',assistant:'DSH \u8f93\u51fa',tool:'\u5de5\u5177\u8c03\u7528','tool-result':'\u5de5\u5177\u8f93\u51fa',approval:'\u7b49\u5f85\u6279\u51c6','approval-result':'\u6279\u51c6\u7ed3\u679c','turn-end':'\u672c\u8f6e\u7ed3\u675f'})[record.type]||record.type}
    function updateWorkspaceMessageAvailability(){const input=$('#workspace-message-input'),send=$('#workspace-message-form button'),enabled=Boolean(selectedWorkspace?.detailAuthorized&&selectedWorkspaceSession);input.disabled=!enabled;send.disabled=!enabled;if(!enabled)input.value='';input.placeholder=selectedWorkspace?.detailAuthorized?'\u9009\u62e9\u4e00\u4e2a\u4f1a\u8bdd\u540e\u53ef\u53d1\u9001\u6d88\u606f':'\u672c\u673a\u6388\u6743\u6b64\u5de5\u4f5c\u533a\u540e\u53ef\u53d1\u9001\u6d88\u606f'}
    function renderWorkspaceRecords(session){selectedWorkspaceSession=session;const meta=workspaceState(session.state);$('#workspace-record-head').innerHTML=`${workspaceLamp(session.state,'workspace-record-state')}<span>${escapeHtml(session.title||'\u672a\u547d\u540d\u4f1a\u8bdd')} · ${session.turns||0} \u8f6e · ${escapeHtml(meta.label)} · \u5b9e\u65f6\u8f93\u51fa</span>`;const records=(Array.isArray(session.records)?session.records:[]).slice().sort((a,b)=>(Number(a.t)||0)-(Number(b.t)||0));$('#workspace-record-list').innerHTML=records.length?records.map(record=>`<article class="workspace-record record-${escapeHtml(record.type)}"><header><b>${escapeHtml(workspaceRecordLabel(record))}${record.name?` · ${escapeHtml(record.name)}`:''}</b><time>${record.t?new Date(record.t).toLocaleString('zh-CN',{hour12:false}):''}</time></header>${record.text?`<pre>${escapeHtml(record.text)}</pre>`:''}${record.model?`<small>${escapeHtml(record.model)}</small>`:''}</article>`).join(''):'<div class="empty-picker">\u8fd9\u4e2a\u4f1a\u8bdd\u6682\u65e0\u53ef\u663e\u793a\u8f93\u51fa。</div>';const list=$('#workspace-record-list');requestAnimationFrame(()=>{list.scrollTop=list.scrollHeight});updateWorkspaceMessageAvailability()}
    function openWorkspaceDetail(item,preferredSessionId=''){const previousSessionId=preferredSessionId||selectedWorkspaceSession?.id||'';selectedWorkspace=item;selectedWorkspaceSession=null;$('#workspace-detail-title').textContent=item.name||'\u5de5\u4f5c\u533a\u8be6\u60c5';$('#workspace-detail-kicker').textContent=`DSH WORKSPACE · ${item.key} · \u6bcf 10 \u79d2\u5237\u65b0`;const sessions=Array.isArray(item.detailSessions)?item.detailSessions:[],root=$('#workspace-session-list'),layout=$('#workspace-detail-modal .workspace-detail-layout');layout.classList.toggle('is-locked',!item.detailAuthorized);if(!item.detailAuthorized){root.innerHTML='<div class="workspace-detail-locked"><b>\u672c\u673a\u4ec5\u6388\u6743\u4e86\u5de5\u4f5c\u533a\u6c47\u603b</b><p>\u8bf7\u5728 DSH \u7684「\u6d3b\u52a8\u7edf\u8ba1 · \u603b\u8bbe\u7f6e · \u751f\u6d3b\u770b\u677f\u8fde\u63a5」\u91cd\u65b0\u8f93\u5165\u770b\u677f\u751f\u6210\u7684 6 \u4f4d\u914d\u5bf9\u7801，\u5e76\u52fe\u9009「\u5141\u8bb8\u67e5\u770b\u4f1a\u8bdd\u8be6\u60c5」，\u624d\u4f1a\u5411\u770b\u677f\u4f20\u8f93\u5b9e\u65f6\u8f93\u51fa。</p></div>';$('#workspace-record-head').textContent='\u5b8c\u6210\u8be6\u60c5\u6388\u6743\u540e\u53ef\u67e5\u770b\u5b9e\u65f6\u8f93\u51fa';$('#workspace-record-list').innerHTML='';}else{root.innerHTML=sessions.length?sessions.map((session,index)=>`<button type="button" data-session-index="${index}">${workspaceLamp(session.state)}<span><b>${escapeHtml(session.title||'\u672a\u547d\u540d\u4f1a\u8bdd')}</b><small>${escapeHtml(session.id.slice(0,8))} · ${session.turns||0} \u8f6e · ${escapeHtml(workspaceState(session.state).label)}</small></span></button>`).join(''):'<div class="empty-picker">\u6b64\u5de5\u4f5c\u533a\u6682\u65e0\u4f1a\u8bdd。</div>';root.querySelectorAll('[data-session-index]').forEach(button=>button.onclick=()=>{root.querySelectorAll('button').forEach(item=>item.classList.remove('active'));button.classList.add('active');renderWorkspaceRecords(sessions[Number(button.dataset.sessionIndex)])});const target=sessions.findIndex(session=>session.id===previousSessionId);root.querySelector(`[data-session-index="${target>=0?target:0}"]`)?.click()}updateWorkspaceMessageAvailability();$('#workspace-detail-modal').classList.add('show')}
    let workspaceDetailMinimized=false;
    function ensureWorkspaceLauncher(){let button=$('#workspace-detail-launcher');if(!button){button=document.createElement('button');button.id='workspace-detail-launcher';button.className='workspace-detail-launcher';button.type='button';button.textContent='⌘';button.title='恢复 DSH 工作区详情';button.setAttribute('aria-label','恢复 DSH 工作区详情');button.onclick=restoreWorkspaceDetail;document.body.append(button)}return button}
    function minimizeWorkspaceDetail(){if(!selectedWorkspace)return;workspaceDetailMinimized=true;$('#workspace-detail-modal').classList.remove('show');ensureWorkspaceLauncher().classList.add('show')}
    function restoreWorkspaceDetail(){if(!selectedWorkspace)return;workspaceDetailMinimized=false;ensureWorkspaceLauncher().classList.remove('show');$('#workspace-detail-modal').classList.add('show');const list=$('#workspace-record-list');requestAnimationFrame(()=>{list.scrollTop=list.scrollHeight})}
    function closeWorkspaceDetail(){workspaceDetailMinimized=false;selectedWorkspace=null;selectedWorkspaceSession=null;$('#workspace-detail-modal').classList.remove('show');ensureWorkspaceLauncher().classList.remove('show')}
    $('#close-workspace-detail').onclick=closeWorkspaceDetail;const workspaceHead=$('#close-workspace-detail')?.parentElement;if(workspaceHead&&!$('#minimize-workspace-detail')){const minimize=document.createElement('button');minimize.id='minimize-workspace-detail';minimize.className='more';minimize.type='button';minimize.textContent='−';minimize.title='最小化工作区详情';workspaceHead.insertBefore(minimize,$('#close-workspace-detail'));minimize.onclick=minimizeWorkspaceDetail}$('#workspace-detail-modal').onclick=event=>{if(event.target===$('#workspace-detail-modal'))closeWorkspaceDetail()};$('#workspace-message-form').onsubmit=async event=>{event.preventDefault();const input=$('#workspace-message-input'),message=input.value.trim(),button=event.currentTarget.querySelector('button');if(!message||!selectedWorkspace||!selectedWorkspaceSession)return;button.disabled=true;try{const response=await oidcFetch('config.php?action=workspace-command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceKey:selectedWorkspace.key,sessionId:selectedWorkspaceSession.id,message})});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||`HTTP ${response.status}`);input.value='';notice('消息已入队，本地 DSH 将在 10 秒内领取');setTimeout(()=>syncWorkspaces(),12000)}catch(error){notice(`发送失败：${error.message}`)}finally{button.disabled=false}};
    function workspaceFailure(error){workspaceSnapshot=null;$('#workspace-status').textContent='连接失败';$('#workspace-list').innerHTML=`<div class="workspace-error"><b>无法读取 DSH 工作区</b><small>${escapeHtml(error.message||String(error))}</small></div>`}
    async function syncWorkspaces(options={}){
      if(workspaceSyncing)return;workspaceSyncing=true;const button=$('#workspace-refresh');if(button)button.classList.add('is-spinning');
      try{const response=await oidcFetch('config.php?action=workspaces',{cache:'no-store'});let data=null;try{data=await response.json()}catch(error){throw new Error(`工作区接口返回 HTTP ${response.status}`)}if(!response.ok||!data.ok)throw new Error(data.error||`工作区接口返回 HTTP ${response.status}`);renderWorkspaces(data);if(options.notice)notice('工作区状态已刷新')}catch(error){if(!readOidcSession())return;workspaceFailure(error);if(options.notice)notice(`工作区刷新失败：${error.message}`)}finally{workspaceSyncing=false;if(button)button.classList.remove('is-spinning')}}
    function beginWorkspaceSync(){if(workspaceTimer)clearInterval(workspaceTimer);syncWorkspaces();workspaceTimer=setInterval(syncWorkspaces,10000)}
    $('#workspace-refresh').onclick=()=>syncWorkspaces({notice:true});

    async function api(path,_cfg,options={}){if(!HA?.url||!HA?.token)throw new Error('Home Assistant 私密配置尚未由管理员解锁');const headers={Authorization:'Bearer '+HA.token,...(options.headers||{})};if(options.body)headers['Content-Type']='application/json';const r=await fetch(HA.url.replace(/\/$/,'')+path,{...options,headers});if(!r.ok){const body=(await r.text()).replace(/\s+/g,' ').slice(0,500);throw new Error(`${options.method||'GET'} ${path} 返回 HTTP ${r.status}${body?`：${body}`:''}`)}try{return await r.json()}catch{throw new Error(`${options.method||'GET'} ${path} 返回了无法解析的 JSON 响应`)}}
    function registrySocketUrl(){const url=new URL(HA.url);url.protocol=url.protocol==='https:'?'wss:':'ws:';url.pathname=url.pathname.replace(/\/$/,'')+'/api/websocket';url.search='';url.hash='';return url.toString()}
    function registryCommand(type){return new Promise((resolve,reject)=>{const socket=new WebSocket(registrySocketUrl()),timer=setTimeout(()=>{socket.close();reject(new Error('区域注册表同步超时'))},10000);let settled=false;const fail=message=>{if(settled)return;settled=true;clearTimeout(timer);socket.close();reject(new Error(message))};socket.onmessage=event=>{try{const message=JSON.parse(event.data);if(message.type==='auth_required')socket.send(JSON.stringify({type:'auth',access_token:HA.token}));else if(message.type==='auth_invalid')fail('Home Assistant WebSocket 认证失败');else if(message.type==='auth_ok')socket.send(JSON.stringify({id:1,type}));else if(message.type==='result'&&message.id===1){if(settled)return;settled=true;clearTimeout(timer);socket.close();message.success?resolve(message.result):reject(new Error(message.error?.message||`${type} 读取失败`))}}catch(error){fail('Home Assistant WebSocket 返回了无效数据')}};socket.onerror=()=>fail('无法连接 Home Assistant WebSocket')})}
    async function syncRegistry(force=false){if(!force&&registrySyncedAt&&Date.now()-registrySyncedAt<5*60*1000)return registry;const [areas,devices,entities]=await Promise.all([registryCommand('config/area_registry/list'),registryCommand('config/device_registry/list'),registryCommand('config/entity_registry/list')]);registry={areas:Array.isArray(areas)?areas:[],devices:Array.isArray(devices)?devices:[],entities:Array.isArray(entities)?entities:[]};registrySyncedAt=Date.now();return registry}
    const escapeHtml=s=>String(s||'').replace(/[&<>'\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
    const TODO_ENTITY='todo.login_ren_wu';
    function agendaError(title,detail){$('#agenda-source').textContent='MS365 To Do 同步失败';$('#agenda-list').innerHTML=`<div class="agenda-row"><span class="agenda-time">!</span><div><div class="agenda-title">${escapeHtml(title)}</div><div class="agenda-meta">${escapeHtml(detail)}</div></div><span class="tag life">错误</span></div>`}
    function renderTodos(todos,listName){$('#agenda-list').innerHTML='';$('#agenda-source').textContent='MS365 To Do';if(!todos.length){$('#agenda-list').innerHTML='<div class="agenda-row"><span class="agenda-time">✓</span><div><div class="agenda-title">没有未完成任务</div><div class="agenda-meta">todo.login_ren_wu 已成功同步</div></div><span class="tag life">MS365 To Do</span></div>';return}$('#agenda-list').innerHTML=todos.slice(0,3).map(todo=>{const due=todo.due?.dateTime||todo.due||todo.due_date;let dueText='未设置截止日期';if(due){const d=new Date(due);dueText=Number.isNaN(d.getTime())?String(due):'截止 '+d.toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})}return `<div class="agenda-row"><span class="agenda-time">待办</span><div><div class="agenda-title">${escapeHtml(todo.subject||todo.summary||todo.title||'未命名任务')}</div><div class="agenda-meta">${escapeHtml(dueText)}</div></div><span class="tag life">${escapeHtml(listName)}</span></div>`}).join('')}
    async function syncTodo(states,cfg){const preferred=states.find(s=>s.entity_id===TODO_ENTITY);if(!preferred){const ids=states.filter(s=>s.entity_id.startsWith('todo.')).map(s=>s.entity_id).join(', ')||'未发现任何 todo.* 实体';agendaError(`找不到实体 ${TODO_ENTITY}`,`Home Assistant 当前待办实体：${ids}`);return}const listName=label(preferred),fromState=preferred.attributes.all_todos||preferred.attributes.items;if(Array.isArray(fromState)){renderTodos(fromState,listName);return}try{const result=await api('/api/services/todo/get_items?return_response',cfg,{method:'POST',body:JSON.stringify({entity_id:TODO_ENTITY,status:'needs_action'})});const data=result.service_response?.[TODO_ENTITY]||result[TODO_ENTITY]||{};if(!Array.isArray(data.items))throw new Error(`服务响应中未找到 ${TODO_ENTITY}.items：${JSON.stringify(result).slice(0,500)}`);renderTodos(data.items,listName)}catch(err){console.error('MS365 To Do 同步失败：',err);agendaError('无法读取 MS365 To Do 任务',err.message)}}
    function calendarFailure(error){
      const message=error?.message||String(error);
      const cors=/failed to fetch|cors|networkerror/i.test(message);
      $('#agenda-source').textContent=cors?'日历跨域未授权':'日历同步失败';
      $('#agenda-list').innerHTML=`<div class="agenda-row"><span class="agenda-time">!</span><div><div class="agenda-title">${cors?'无法读取 Home Assistant 日历':'日历暂时无法同步'}</div><div class="agenda-meta">${cors?'home.mcylyr.cn 的 OPTIONS 响应缺少 Access-Control-Allow-Origin；需在反向代理放行 life.mcylyr.cn':'请稍后刷新重试'}</div></div><span class="tag">日历</span></div>`;
      console.error('Home Assistant 日历同步失败：',error);
    }
    async function syncCalendar(states,cfg){try{const calendars=states.filter(s=>s.entity_id.startsWith('calendar.'));if(!calendars.length)return;const start=new Date(),end=new Date();start.setHours(0,0,0,0);end.setHours(23,59,59,999);const result=await api('/api/services/calendar/get_events?return_response',cfg,{method:'POST',body:JSON.stringify({entity_id:calendars.map(s=>s.entity_id),start_date_time:start.toISOString(),end_date_time:end.toISOString()})});const response=result.service_response||result;const events=calendars.flatMap(cal=>(response[cal.entity_id]?.events||[]).map(e=>({...e,calendar:label(cal)}))).sort((a,b)=>new Date(a.start.dateTime||a.start.date)-new Date(b.start.dateTime||b.start.date)).slice(0,4);if(!events.length)return;$('#agenda-source').textContent='Home Assistant 日历';$('#agenda-list').innerHTML=events.map(e=>{const allDay=!!e.start.date,time=allDay?'全天':new Date(e.start.dateTime).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});return `<div class="agenda-row"><span class="agenda-time">${time}</span><div><div class="agenda-title">${escapeHtml(e.summary)}</div><div class="agenda-meta">${escapeHtml(e.location||e.calendar)}</div></div><span class="tag">${escapeHtml(e.calendar)}</span></div>`}).join('')}catch(error){calendarFailure(error)}}
    async function sync(cfg){if(syncing)return;syncing=true;try{const states=await api('/api/states',cfg);latestStates=states;try{await syncRegistry()}catch(error){console.warn('Home Assistant 区域注册表同步失败，已降级为全部实体列表：',error)}const temp=environmentSensors(states,'temperature')[0]||entity(states,'sensor',['temperature','温度']),humidity=environmentSensors(states,'humidity')[0]||entity(states,'sensor',['humidity','湿度']);if(value(temp))$('#temperature').textContent=value(temp);$('#environment').textContent=[humidity&&value(humidity)?'湿度 '+value(humidity)+(humidity.attributes.unit_of_measurement||'%'):'已连接 Home Assistant','刚刚同步'].filter(Boolean).join(' · ');$('#ha-status').textContent=registry.areas.length?'实时同步 · 区域已连接':'实时同步';renderEnvironmentSlots(states);renderQuick(states);renderDevices(states);await syncCalendar(states,cfg).catch(()=>{});await syncTodo(states,cfg) }finally{syncing=false}}
    function beginAutoSync(cfg){if(syncTimer)clearInterval(syncTimer);syncTimer=setInterval(()=>sync(cfg).catch(()=>{$('#ha-status').textContent='同步失败'}),30000)}
    $('#connect-form').onsubmit=async e=>{
      e.preventDefault();
      if(!HA?.url||!HA?.token){notice('请使用 Authentik 管理员账号登录以解锁 Home Assistant');return}
      try{
        notice('正在连接…');
        await sync(HA);
        beginAutoSync(HA);
        hideModal();
        notice(`Home Assistant 已连接，读取到 ${latestStates.length} 个实体、${registry.areas.length} 个区域`)
      }catch(err){notice(err.message)}
    };
    loadRuntimeConfig().then(()=>{setLoginReady(true);return authenticate()}).then(async ok=>{
      if(!ok){if(await trySilentSignIn())return;return}
      if(!readOidcSession())return;
      setLoaderStage('正在验证管理员权限','正在安全读取你的私密生活配置…',2);
      beginWorkspaceSync();
      try{await loadPrivateRuntimeConfig()}catch(error){
        $('#ha-status').textContent='管理员权限未解锁';
        $('#environment').textContent='已登录 · Home Assistant 私密配置受保护';
        notice(error.message);
        finishDashboardLoad();
        return;
      }
      setLoaderStage('正在连接生活中枢','正在同步家庭环境、设备与今日安排…',3);
      try{await sync(HA);beginAutoSync(HA);finishDashboardLoad()}catch(error){finishDashboardLoad();notice('Home Assistant 连接失败，请检查 .env 与 CORS 设置')}
    }).catch(e=>{setLoginReady(false);loginError(e.message);finishDashboardLoad()});
    document.querySelectorAll('.quick-grid button').forEach(b=>b.addEventListener('click',()=>{if(readOidcSession())return;b.classList.toggle('on');b.querySelector('small').textContent=b.classList.contains('on')?'已开启':'已关闭'}));
    /* ===== 外观主题：日间 / 夜间 / 跟随系统 ===== */
    const themeKey='life-hub-theme',themeMedia=matchMedia('(prefers-color-scheme: dark)');
    function resolvedTheme(){const mode=localStorage.getItem(themeKey)||'auto';return mode==='dark'||(mode==='auto'&&themeMedia.matches)?'dark':'light'}
    function applyTheme(){const theme=resolvedTheme();document.documentElement.dataset.theme=theme;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#0e1311':'#101516')}
    function initTheme(){applyTheme();themeMedia.addEventListener?.('change',()=>{if((localStorage.getItem(themeKey)||'auto')==='auto')applyTheme()})}
    function renderThemeSettings(){const mode=localStorage.getItem(themeKey)||'auto';$('#theme-options').querySelectorAll('[data-theme-mode]').forEach(btn=>{const active=btn.dataset.themeMode===mode;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',String(active))})}
    $('#theme-options').addEventListener('click',e=>{const btn=e.target.closest('[data-theme-mode]');if(!btn)return;localStorage.setItem(themeKey,btn.dataset.themeMode);applyTheme();renderThemeSettings();notice(btn.dataset.themeMode==='auto'?'外观已切换为跟随系统':btn.dataset.themeMode==='dark'?'已切换到夜间模式':'已切换到日间模式')});
    initTheme();

    /* ===== 纪念日与倒数 ===== */
    const countdownsKey='life-hub-countdowns';
    function countdowns(){try{const list=JSON.parse(localStorage.getItem(countdownsKey)||'[]');return Array.isArray(list)?list.filter(i=>i&&i.name&&/^\d{4}-\d{2}-\d{2}$/.test(i.date)):[]}catch(err){localStorage.removeItem(countdownsKey);return []}}
    function saveCountdowns(list){try{localStorage.setItem(countdownsKey,JSON.stringify(list))}catch(err){notice('浏览器阻止了纪念日保存')}}
    function countdownNext(item){const [y,m,d]=item.date.split('-').map(Number);if(!m||!d)return null;const today=new Date();today.setHours(0,0,0,0);const thisYear=new Date(today.getFullYear(),m-1,d);if(!item.yearly)return thisYear<today?null:thisYear;let next=thisYear;if(next<today){next=new Date(next);next.setFullYear(next.getFullYear()+1)}return next}
    function countdownDays(item){const next=countdownNext(item);if(!next)return null;const today=new Date();today.setHours(0,0,0,0);return Math.round((next-today)/86400000)}
    function renderCountdowns(){const list=countdowns().map(i=>({...i,days:countdownDays(i)})).filter(i=>i.days!==null).sort((a,b)=>a.days-b.days);$('#countdown-status').textContent=list.length?`${list.length} 项`:'未添加';$('#countdown-list').innerHTML=list.length?list.map(i=>{const d=new Date(i.date+'T00:00:00'),isToday=i.days===0;return `<div class="countdown-item ${isToday?'today':''}"><div class="countdown-copy"><b>${escapeHtml(i.name)}</b><small>${d.getMonth()+1} 月 ${d.getDate()} 日${i.yearly?' · 每年':''}</small></div><span class="countdown-pill">${isToday?'就是今天':`还有 ${i.days} 天`}</span></div>`}).join(''):'<div class="empty-picker">在设置中添加生日、节日或重要日子。</div>'}
    function renderCountdownSettings(){const root=$('#countdown-settings'),list=countdowns();root.innerHTML=list.length?list.map((i,idx)=>`<div class="countdown-setting-row"><span>${escapeHtml(i.name)}</span><small>${escapeHtml(i.date)}${i.yearly?' · 每年':''} · 还有 ${countdownDays(i)??'?'} 天</small><button type="button" data-del="${idx}" aria-label="删除 ${escapeHtml(i.name)}">×</button></div>`).join(''):'<div class="countdown-empty">还没有添加任何纪念日。</div>';root.querySelectorAll('[data-del]').forEach(btn=>btn.onclick=()=>{const next=countdowns();const removed=next.splice(Number(btn.dataset.del),1)[0];saveCountdowns(next);renderCountdownSettings();renderCountdowns();notice(`已删除「${removed?.name||'纪念日'}」`)})}
    $('#countdown-form').onsubmit=e=>{e.preventDefault();const name=$('#countdown-name').value.trim().slice(0,16),date=$('#countdown-date').value;if(!name||!/^\d{4}-\d{2}-\d{2}$/.test(date)){notice('请填写名称和日期');return}const list=countdowns();if(list.some(i=>i.name===name&&i.date===date)){notice('这个纪念日已经存在');return}list.push({name,date,yearly:$('#countdown-yearly').checked});saveCountdowns(list);$('#countdown-name').value='';$('#countdown-date').value='';renderCountdownSettings();renderCountdowns();notice('纪念日已添加')};

    /* ===== 天气与预报（Open-Meteo 免费开放接口，无需 Key） ===== */
    const weatherCityKey='life-hub-weather-city',weatherCacheKey='life-hub-weather-cache';
    let weatherSummary='';
    const WMO={0:['☀','晴'],1:['🌤','大致晴朗'],2:['⛅','多云'],3:['☁','阴'],45:['🌫','雾'],48:['🌫','雾凇'],51:['🌦','小毛雨'],53:['🌦','毛雨'],55:['🌧','大毛雨'],61:['🌦','小雨'],63:['🌧','中雨'],65:['🌧','大雨'],66:['🌧','冻雨'],67:['🌧','冻雨'],71:['🌨','小雪'],73:['🌨','中雪'],75:['❄','大雪'],77:['🌨','雪粒'],80:['🌦','阵雨'],81:['🌧','强阵雨'],82:['⛈','暴雨'],85:['🌨','阵雪'],86:['❄','阵雪'],95:['⛈','雷雨'],96:['⛈','雷雨伴冰雹'],99:['⛈','雷雨伴冰雹']};
    function syncWeatherSettings(){$('#weather-city').value=localStorage.getItem(weatherCityKey)||''}
    function renderWeather(cached){const {city,wx}=cached,[icon,desc]=WMO[wx.current?.weather_code]||['◌','未知'],cur=wx.current||{},daily=wx.daily||{time:[],weather_code:[],temperature_2m_min:[],temperature_2m_max:[]};$('#weather-status').textContent=city;$('#weather-body').innerHTML=`<div class="weather-now"><span class="weather-icon">${icon}</span><div class="weather-main"><b>${cur.temperature_2m??'--'}°C</b><small>${desc} · 体感 ${cur.apparent_temperature??'--'}°C</small></div><div class="weather-side"><small>湿度 ${cur.relative_humidity_2m??'--'}%</small></div></div><div class="weather-days">${(daily.time||[]).slice(1,4).map((t,i)=>{const [di,dd]=WMO[daily.weather_code?.[i+1]]||['◌','—'];const wd='日一二三四五六'[new Date(t+'T00:00:00').getDay()];return `<div class="weather-day"><span>${di}</span><small>周${wd}</small><b>${dd}</b><small>${Math.round(daily.temperature_2m_min[i+1]??0)}° / ${Math.round(daily.temperature_2m_max[i+1]??0)}°</small></div>`}).join('')}</div>`;weatherSummary=`${city}当前${desc}，${cur.temperature_2m}°C（体感 ${cur.apparent_temperature}°C，湿度 ${cur.relative_humidity_2m}%），未来三天 ${(daily.time||[]).slice(1,4).map((t,i)=>`${WMO[daily.weather_code?.[i+1]]?.[1]||'未知'}${Math.round(daily.temperature_2m_max[i+1]??0)}°`).join('、')}`}
    async function fetchWeather(force=false){const city=(localStorage.getItem(weatherCityKey)||'').trim();if(!city){$('#weather-status').textContent='待配置城市';$('#weather-body').innerHTML='<div class="empty-picker">在设置中填写城市后，展示当前天气与三日预报（Open-Meteo 免费开放接口，无需注册）。</div>';weatherSummary='';return}let cached=null;try{cached=JSON.parse(sessionStorage.getItem(weatherCacheKey)||'null')}catch(err){sessionStorage.removeItem(weatherCacheKey)}if(!force&&cached&&cached.city===city&&Date.now()-cached.at<30*60*1000){renderWeather(cached);return}$('#weather-status').textContent='正在获取 '+city+'…';try{const geo=await (await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=zh&format=json`)).json();const loc=geo.results?.[0];if(!loc)throw new Error(`找不到城市「${city}」，请换个写法试试`);const wx=await (await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${loc.latitude}&longitude=${loc.longitude}&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min&timezone=auto&forecast_days=4`)).json();const payload={at:Date.now(),city:loc.name,wx};sessionStorage.setItem(weatherCacheKey,JSON.stringify(payload));renderWeather(payload)}catch(err){$('#weather-status').textContent='获取失败';$('#weather-body').innerHTML=`<div class="empty-picker">${escapeHtml(err.message==='Failed to fetch'?'无法连接 Open-Meteo，请检查网络后重试':err.message)}</div>`}}
    $('#weather-form').onsubmit=e=>{e.preventDefault();const city=$('#weather-city').value.trim().slice(0,24);if(!city){notice('请输入城市名称');return}localStorage.setItem(weatherCityKey,city);sessionStorage.removeItem(weatherCacheKey);notice(`天气城市已保存为「${city}」`);fetchWeather(true)};

    /* ===== AI 助手（OpenAI 兼容接口，可自配地址 / Key / 模型） ===== */
    const aiConfigKey='life-hub-ai-config';
    let aiHistory=[];
    function aiConfig(){try{const cfg=JSON.parse(localStorage.getItem(aiConfigKey)||'null');return cfg&&cfg.baseUrl&&cfg.apiKey&&cfg.model?cfg:null}catch(err){localStorage.removeItem(aiConfigKey);return null}}
    function updateAiLabel(){const cfg=aiConfig();$('#ai-model-label').textContent=cfg?.model||'未配置模型';$('#ai-dot').classList.toggle('ok',Boolean(cfg))}
    function syncAiSettings(){const raw=(()=>{try{return JSON.parse(localStorage.getItem(aiConfigKey)||'null')||{}}catch(err){return {}}})(),sel=$('#ai-model');$('#ai-base').value=raw.baseUrl||'';$('#ai-key').value=raw.apiKey||'';if(raw.model&&!sel.querySelector(`option[value="${raw.model}"]`))sel.insertAdjacentHTML('beforeend',`<option value="${escapeHtml(raw.model)}">${escapeHtml(raw.model)}</option>`);sel.value=raw.model||'';updateAiLabel()}
    const aiUiKey='life-hub-ai-ui',aiRefreshMs=30000;let aiRefreshTimer=0,aiMinimized=false;
    function readAiUi(){try{return JSON.parse(localStorage.getItem(aiUiKey)||'{}')}catch(err){return {}}}
    function saveAiUi(){try{localStorage.setItem(aiUiKey,JSON.stringify({minimized:aiMinimized,width:$('#ai-panel')?.offsetWidth,height:$('#ai-panel')?.offsetHeight}))}catch(err){}}
    function scrollAiToBottom(){const box=$('#ai-messages');if(box)requestAnimationFrame(()=>{box.scrollTop=box.scrollHeight})}
    function setupAiControls(){const panel=$('#ai-panel');if(!panel)return;const saved=readAiUi();if(saved.width&&saved.height){panel.style.width=Math.min(Math.max(Number(saved.width),300),window.innerWidth-28)+'px';panel.style.height=Math.min(Math.max(Number(saved.height),300),window.innerHeight-28)+'px'}let launcher=$('#ai-launcher');if(!launcher){launcher=document.createElement('button');launcher.id='ai-launcher';launcher.className='ai-launcher';launcher.type='button';launcher.setAttribute('aria-label','打开 AI 助手');launcher.title='打开 AI 助手';launcher.textContent='✦';document.body.append(launcher)}let actions=panel.querySelector('.ai-head-actions');if(!actions){actions=document.createElement('div');actions.className='ai-head-actions';const close=$('#ai-close');if(close){close.parentNode.insertBefore(actions,close);actions.append(close)}}let minimize=$('#ai-minimize');if(!minimize){minimize=document.createElement('button');minimize.id='ai-minimize';minimize.className='more';minimize.type='button';minimize.setAttribute('aria-label','最小化 AI 助手');minimize.textContent='−';actions?.prepend(minimize)}if(!panel.dataset.resizeBound){panel.dataset.resizeBound='1';new ResizeObserver(()=>{if(!aiMinimized)saveAiUi()}).observe(panel)}}
    function renderAiMinimized(){setupAiControls();const panel=$('#ai-panel'),launcher=$('#ai-launcher');if(!panel||!launcher)return;panel.classList.toggle('minimized',aiMinimized);launcher.classList.toggle('is-hidden',!aiMinimized);panel.setAttribute('aria-hidden',String(aiMinimized));}
    function openAiPanel(){aiMinimized=false;$('#ai-panel').classList.add('open');saveAiUi();renderAiMinimized();if(!aiHistory.length)renderAiMessages();scrollAiToBottom();$('#ai-question').focus()}
    function minimizeAiPanel(){aiMinimized=true;saveAiUi();renderAiMinimized()}
    function closeAiPanel(){minimizeAiPanel()}
    function collectDashboardContext(){const d=new Date(),lines=[`现在是 ${d.toLocaleString('zh-CN',{hour12:false})}（${$('#today').textContent}），用户称呼 ${displayName()}。`];lines.push(`家庭环境：室内 ${$('#temperature').textContent}°C；${$('#environment').textContent}；连接状态 ${$('#ha-status').textContent}。`);if(weatherSummary)lines.push(`天气：${weatherSummary}。`);if(workspaceSnapshot?.workspaces?.length)lines.push(`工作区：${workspaceSnapshot.workspaces.slice(0,8).map(item=>`${item.name}${workspaceStateMeta[item.state]?.label||'未知'}（${relativeActivity(item.ageMs)}）`).join('、')}。`);const onDevices=latestStates.filter(s=>canControl(s)&&isActive(s)).slice(0,10).map(s=>label(s));if(latestStates.length)lines.push(`Home Assistant：${latestStates.length} 个实体、${registry.areas.length} 个区域；当前开启：${onDevices.length?onDevices.join('、'):'无'}。`);const agenda=[...($('#agenda-list')?.querySelectorAll('.agenda-row')||[])].map(r=>r.textContent.replace(/\s+/g,' ').trim()).slice(0,5);if(agenda.length)lines.push(`今日安排：${agenda.join('；')}。`);const cds=countdowns().map(i=>({name:i.name,days:countdownDays(i)})).filter(i=>i.days!==null);if(cds.length)lines.push(`纪念日：${cds.map(i=>`${i.name}${i.days===0?'就是今天':`还有 ${i.days} 天`}`).join('、')}。`);return lines.join('\n')}
    function renderAiMessages(state){const box=$('#ai-messages');if(!aiHistory.length){box.innerHTML=`<div class="ai-empty"><div class="ai-empty-icon">✦</div><p>我可以读取看板数据与你对话。配置好 AI 后，问问我「家里现在多少度」「总结一下今天的安排」。</p><div class="ai-hints"><button class="ai-hint" type="button">家里现在什么情况？</button><button class="ai-hint" type="button">总结一下我今天的安排</button><button class="ai-hint" type="button">最近有什么值得纪念的日子？</button></div></div>`;box.querySelectorAll('.ai-hint').forEach(btn=>btn.onclick=()=>{$('#ai-question').value=btn.textContent.trim();$('#ai-form').requestSubmit()});return}box.innerHTML=aiHistory.map(m=>`<div class="ai-msg ${m.role==='user'?'user':'bot'}">${escapeHtml(m.content)}</div>`).join('')+(state==='thinking'?'<div class="ai-msg bot thinking">正在思考…</div>':'');scrollAiToBottom()}
    async function sendAiMessage(text){const cfg=aiConfig();if(!cfg){notice('请先在设置中配置 AI 助手');closeAiPanel();setView('settings');return}aiHistory.push({role:'user',content:text});renderAiMessages('thinking');try{const r=await fetch(cfg.baseUrl+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+cfg.apiKey},body:JSON.stringify({model:cfg.model,messages:[{role:'system',content:'你是"生活中枢"个人看板的内置 AI 助手，用简洁的中文回答。以下是看板的实时数据，回答时优先依据这些数据：\n'+collectDashboardContext()+'\n如果用户想控制设备，引导其在看板的快捷控制或 Home Assistant 区域卡片中操作。'},...aiHistory.slice(-20)],temperature:.6})});if(!r.ok)throw new Error(`接口返回 HTTP ${r.status}`);const data=await r.json(),reply=data.choices?.[0]?.message?.content?.trim();if(!reply)throw new Error('模型没有返回内容');aiHistory.push({role:'assistant',content:reply});renderAiMessages()}catch(err){aiHistory.pop();renderAiMessages();notice('AI 请求失败：'+(err.message==='Failed to fetch'?'无法连接接口，请检查地址与 CORS 设置':err.message))}}
    aiMinimized=Boolean(readAiUi().minimized);renderAiMinimized();
    $('#ai-open').onclick=e=>{e.stopPropagation();openAiPanel()};$('#ai-launcher').onclick=openAiPanel;$('#ai-minimize').onclick=minimizeAiPanel;
    $('#ai-close').onclick=closeAiPanel;
    $('#ai-form').onsubmit=e=>{e.preventDefault();const text=$('#ai-question').value.trim();if(!text)return;$('#ai-question').value='';sendAiMessage(text)};
    $('#ai-fetch-models').onclick=async()=>{const base=$('#ai-base').value.trim().replace(/\/+$/,''),key=$('#ai-key').value.trim(),status=$('#ai-config-status');if(!base||!key){status.textContent='请先填写接口地址和 API Key';return}if(!/^https?:\/\//.test(base)){status.textContent='接口地址需以 http(s):// 开头';return}status.textContent='正在拉取模型列表…';try{const r=await fetch(base+'/models',{headers:{Authorization:'Bearer '+key}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json(),ids=(Array.isArray(data.data)?data.data:[]).map(m=>m&&m.id).filter(Boolean);if(!ids.length)throw new Error('接口未返回任何模型');const sel=$('#ai-model'),current=sel.value;sel.innerHTML=ids.map(id=>`<option value="${escapeHtml(id)}">${escapeHtml(id)}</option>`).join('');if(ids.includes(current))sel.value=current;status.textContent=`已获取 ${ids.length} 个模型，请选择后保存`}catch(err){status.textContent='拉取失败：'+(err.message==='Failed to fetch'?'无法连接接口，请检查地址与 CORS':err.message)}};
    $('#ai-config-form').onsubmit=e=>{e.preventDefault();const baseUrl=$('#ai-base').value.trim().replace(/\/+$/,''),apiKey=$('#ai-key').value.trim(),model=$('#ai-model').value,status=$('#ai-config-status');if(!/^https?:\/\//.test(baseUrl)){status.textContent='接口地址需以 http(s):// 开头';return}if(!apiKey){status.textContent='请填写 API Key';return}if(!model){status.textContent='请先拉取并选择模型';return}try{localStorage.setItem(aiConfigKey,JSON.stringify({baseUrl,apiKey,model}))}catch(err){status.textContent='浏览器阻止了保存';return}updateAiLabel();status.textContent='AI 配置已保存';notice('AI 助手配置已保存')};

    renderCountdowns();
    renderAiMessages();setInterval(()=>{if(!aiMinimized)syncWorkspaces();fetchWeather();},aiRefreshMs);
    fetchWeather();
    setInterval(renderCountdowns,60*60*1000);
    setInterval(fetchWeather,30*60*1000);
